/*
 * Copyright (C) 2021 - 2024, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 */
using SanteDB.Core.Model.Acts;
using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.Model.Extensibility;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Acts
{
    /// <summary>
    /// Represents a care pathway identifier
    /// </summary>
    [Table("cp_def_tbl")]
    public class DbCarePathwayDefinition : DbNonVersionedBaseData
    {

        /// <summary>
        /// Gets or sets the primary key
        /// </summary>
        [Column("pth_id"), PrimaryKey, AutoGenerated, NotNull]
        public override Guid Key { get; set; }

        /// <summary>
        /// Get or sets the mnemonic
        /// </summary>
        [Column("mnemonic"), Unique, NotNull]
        public string Mnemonic { get; set; }

        /// <summary>
        /// Get or sets the description
        /// </summary>
        [Column("descr")]
        public string Description { get; set; }

        /// <summary>
        /// Enrolment 
        /// </summary>
        [Column("enrol")]
        public CarePathwayEnrollmentMode EnrollmentMode { get; set; }

        /// <summary>
        /// Get or set the eligibility criteria
        /// </summary>
        [Column("elig")]
        public string EligibilityCriteria { get; set; }

        /// <summary>
        /// Get or set the template key
        /// </summary>
        [Column("tpl_id"), ForeignKey(typeof(DbTemplateDefinition), nameof(DbTemplateDefinition.Key))]
        public Guid? TemplateKey { get; set; }
    }
}
