using SanteDB.Core.Model.Acts;
using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.Model.Extensibility;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Acts
{
    /// <summary>
    /// Represents a care pathway identifier
    /// </summary>
    [Table("cp_def_tbl")]
    public class DbCarePathwayDefinition : DbNonVersionedBaseData
    {

        /// <summary>
        /// Gets or sets the primary key
        /// </summary>
        [Column("pth_id"), PrimaryKey, AutoGenerated, NotNull]
        public override Guid Key { get; set; }

        /// <summary>
        /// Get or sets the mnemonic
        /// </summary>
        [Column("mnemonic"), Unique, NotNull]
        public string Mnemonic { get; set; }

        /// <summary>
        /// Get or sets the description
        /// </summary>
        [Column("descr")]
        public string Description { get; set; }

        /// <summary>
        /// Enrolment 
        /// </summary>
        [Column("enrol")]
        public CarePathwayEnrolmentMode EnrolmentMode { get; set; }

        /// <summary>
        /// Get or set the eligibility criteria
        /// </summary>
        [Column("elig")]
        public string EligibilityCriteria { get; set; }

        /// <summary>
        /// Get or set the template key
        /// </summary>
        [Column("tpl_id"), ForeignKey(typeof(DbTemplateDefinition), nameof(DbTemplateDefinition.Key))]
        public Guid? TemplateKey { get; set; }
    }
}
