/*
 * Copyright (C) 2021 - 2025, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 */

using System;
using SanteDB.OrmLite.Attributes;

namespace SanteDB.Persistence.Data.Model.Notifications
{
    /// <summary>
    /// Represents a notification template parameter.
    /// </summary>
    [Table("nfn_tpl_prm_tbl")]
    public class DbNotificationTemplateParameter : DbIdentified
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="DbNotificationTemplateParameter"/> class.
        /// </summary>
        public DbNotificationTemplateParameter()
        {

        }

        /// <summary>
        /// Gets or sets the key of the parameter.
        /// </summary>
        [Column("tpl_prm_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the notification template key of the parameter.
        /// </summary>
        [Column("nfn_tpl_id"), ForeignKey(typeof(DbNotificationTemplate), nameof(DbNotificationTemplate.Key))]
        public Guid NotificationTemplateKey { get; set; }

        /// <summary>
        /// Gets or sets the name of the parameter.
        /// </summary>
        [Column("prm_name"), NotNull]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the description of the parameter.
        /// </summary>
        [Column("descr")]
        public string Description { get; set; }

    }
}