/*
 * Copyright (C) 2021 - 2025, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 */

using System;
using SanteDB.OrmLite.Attributes;

namespace SanteDB.Persistence.Data.Model.Notifications
{
    /// <summary>
    /// Represents a notification template parameter value.
    /// </summary>
    [Table("prmtr_val_tbl")]
    public class DbNotificationParameterValue : DbNonVersionedBaseData
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="DbNotificationParameterValue"/> class.
        /// </summary>
        public DbNotificationParameterValue()
        {

        }

        /// <summary>
        /// Gets or sets the key of the parameter value.
        /// </summary>
        [Column("prmtr_val_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the notification of the parameter value.
        /// </summary>
        [Column("notif_id"), ForeignKey(typeof(DbNotification), nameof(DbNotification.Key))]
        public Guid Notification { get; set; }

        /// <summary>
        /// Gets or sets the value of the parameter value.
        /// </summary>
        [Column("val")]
        public string Value { get; set; }
    }
}