/*
 * Copyright (C) 2021 - 2025, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 */

using System;
using SanteDB.OrmLite.Attributes;

namespace SanteDB.Persistence.Data.Model.Notifications
{
    /// <summary>
    /// Represents a notification instance parameter.
    /// </summary>
    [Table("nfn_inst_prm_tbl")]
    public class DbNotificationInstanceParameter : DbIdentified
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="DbNotificationInstanceParameter"/> class.
        /// </summary>
        public DbNotificationInstanceParameter()
        {

        }

        /// <summary>
        /// Gets or sets the key of the instance parameter.
        /// </summary>
        [Column("prm_val_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the notification instance key of the instance parameter.
        /// </summary>
        [Column("nfn_inst_id"), ForeignKey(typeof(DbNotificationInstance), nameof(DbNotificationInstance.Key)), NotNull]
        public Guid NotificationInstanceKey { get; set; }

        /// <summary>
        /// Gets or sets the template parameter key of the instance parameter.
        /// </summary>
        [Column("nfn_tpl_prm_id"), ForeignKey(typeof(DbNotificationTemplateParameter), nameof(DbNotificationTemplateParameter.Key)), NotNull]
        public Guid TemplateParameterKey { get; set; }

        /// <summary>
        /// Gets or sets the expression of the instance parameter.
        /// </summary>
        [Column("expr"), NotNull]
        public string Expression { get; set; }
    }
}