using System;
using SanteDB.OrmLite.Attributes;

namespace SanteDB.Persistence.Data.Model.Notifications
{
    /// <summary>
    /// Represents a notification template.
    /// </summary>
    [Table("notification_template_tbl")]
    public class DbNotificationTemplate : DbNonVersionedBaseData
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="DbNotificationTemplate"/> class.
        /// </summary>
        public DbNotificationTemplate()
        {

        }

        /// <summary>
        /// Gets or sets the key of the notification template.
        /// </summary>
        [Column("id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the status of the notification template.
        /// </summary>
        [Column("sts_cd_id")]
        public Guid Status { get; set; }

        /// <summary>
        /// Gets or sets the mnemonic of the notification template.
        /// </summary>
        [Column("mnemonic")]
        public string Mnemonic { get; set; }

        /// <summary>
        /// Gets or sets the name of the notification template.
        /// </summary>
        [Column("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the tags of the notification template.
        /// </summary>
        [Column("tags")]
        public string Tags { get; set; }

    }
}
