/*
 * Copyright (C) 2021 - 2025, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 */

using System;
using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.Model.Concepts;

namespace SanteDB.Persistence.Data.Model.Notifications
{
    /// <summary>
    /// Represents a notification template.
    /// </summary>
    [Table("nfn_tpl_tbl")]
    public class DbNotificationTemplate : DbNonVersionedBaseData
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="DbNotificationTemplate"/> class.
        /// </summary>
        public DbNotificationTemplate()
        {

        }

        /// <summary>
        /// Gets or sets the key of the notification template.
        /// </summary>
        [Column("tpl_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the status key of the notification template.
        /// </summary>
        [Column("sts_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key)), NotNull]
        public Guid StatusKey { get; set; }

        /// <summary>
        /// Gets or sets the mnemonic of the notification template.
        /// </summary>
        [Column("mnemonic"), NotNull]
        public string Mnemonic { get; set; }

        /// <summary>
        /// Gets or sets the name of the notification template.
        /// </summary>
        [Column("tpl_name"), NotNull]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the tags of the notification template.
        /// </summary>
        [Column("tags")]
        public string Tags { get; set; }

    }
}
