<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
    <IsPackable>true</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(VersionNumber)' == ''">
		<VersionNumber>3.1-debug</VersionNumber>
	</PropertyGroup>

  <PropertyGroup>
    <PackageId>SanteDB.Core.TestFramework.FirebirdSQL</PackageId>
    <Title>SanteDB.Core.TestFramework</Title>
    <Version>$(VersionNumber)</Version>
    <Description>Core testing framework for performing unit tests with FirebirdSQL as the provider</Description>
    <Authors>SanteSuite Contributors</Authors>
    <PackageTags>SanteDB</PackageTags>
    <RepositoryUrl>https://github.com/santedb/santedb-api</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Product>SanteDB</Product>
    <Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
    <Company>SanteSuite Contributors</Company>
    <PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
    <PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
    <AssemblyName>SanteDB.Core.TestFramework.FirebirdSQL</AssemblyName>
  </PropertyGroup>
	
  <Choose>
    <When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.TestFramework" Version="$(VersionNumber)" />
			</ItemGroup>
    </When>
    <Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\..\santedb-api\SanteDB.Core.TestFramework\SanteDB.Core.TestFramework.csproj" />
			</ItemGroup>
    </Otherwise>
  </Choose>
	
  <ItemGroup>
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="[9.1.1,10)" />
		<PackageReference Include="NUnit" Version="[4.5.0,5)" />
		<PackageReference Include="NUnit3TestAdapter" Version="[6.1.0,7)" />
  </ItemGroup>
	
  <ItemGroup>
    <EmbeddedResource Include="SanteDB.Core.TestFramework.FirebirdSQL.targets" Pack="true" PackagePath="build" />
    <None Include="..\..\SanteDB.licenseheader" Link="SanteDB.licenseheader" />
		<!--<None Include="firebird\fbclient.dll" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\firebird.conf" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\firebird.msg" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\ib_util.dll" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\icudt52.dll" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\icudt52l.dat" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\icuin52.dll" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\icuuc52.dll" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\IDPLicense.txt" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\IPLicense.txt" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\santedb_test.fdb" Pack="true" PackagePath="build\firebird" />
    <None Include="firebird\plugins\engine12.dll" Pack="true" PackagePath="build\firebird\plugins" />-->
  </ItemGroup>

	<ItemGroup>
		<Content Include="$(MSBuildThisFileDirectory)\firebird\santedb_test.fdb" >
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
    <Content Include="firebird\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>%(Filename)%(Extension)</TargetPath>
      <Pack>true</Pack>
      <PackagePath>build</PackagePath>
		</Content>
    <Content Include="firebird\plugins\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>plugins\%(Filename)%(Extension)</TargetPath>
      <Pack>true</Pack>
      <PackagePath>build</PackagePath>
    </Content>
	</ItemGroup>
</Project>