<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)' == ''">
		<VersionNumber>3.0-debug</VersionNumber>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>SanteDB.Persistence.Data</PackageId>
		<Title>SanteDB.Persistence.Data</Title>
		<Version>$(VersionNumber)</Version>
		<Description>SanteDB CDR Portable Persistence (replaces the legacy SanteDB.Persistence.Data project)</Description>
		<Authors>SanteSuite Contributors</Authors>
		<PackageTags>SanteDB</PackageTags>
		<RepositoryUrl>https://github.com/santedb/santedb-data</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
		<PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
	</PropertyGroup>
	<Choose>
		<When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.OrmLite" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.BI" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.i18n" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Docker.Core" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.i18n" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Matcher" Version="$(VersionNumber)" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
				<ProjectReference Include="..\..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
				<ProjectReference Include="..\..\santedb-orm\SanteDB.OrmLite\SanteDB.OrmLite.csproj" />
				<ProjectReference Include="..\..\santedb-bis\SanteDB.BI\SanteDB.BI.csproj" />
				<ProjectReference Include="..\..\santedb-docker\SanteDB.Docker.Core\SanteDB.Docker.Core.csproj" />
				<ProjectReference Include="..\..\santedb-i18n\SanteDB.Core.i18n\SanteDB.Core.i18n.csproj" />
				<ProjectReference Include="..\..\santedb-match\SanteDB.Matcher\SanteDB.Matcher.csproj" />
			</ItemGroup>
		</Otherwise>
	</Choose>

	<ItemGroup>
		<None Remove="**\*.sql" />
		<None Remove="Map\CdssModelMap.xml" />
		<None Remove="Map\ModelMap.xml" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Map\CdssModelMap.xml" />
		<EmbeddedResource Include="Map\ModelMap.xml" />
		<EmbeddedResource Include="SQL\FBSQL\*.sql" />
		<EmbeddedResource Include="SQL\FBSQL\Updates\*.sql" />
		<EmbeddedResource Include="SQL\PSQL\*.sql" />
		<EmbeddedResource Include="SQL\PSQL\Updates\*.sql" />
		<EmbeddedResource Include="SQL\SQLITE\*.sql" />
		<EmbeddedResource Include="SQL\SQLITE\Updates\*.sql" />
	</ItemGroup>

	

	<ItemGroup>
		<None Include="..\SanteDB.licenseheader" Link="SanteDB.licenseheader" />
		<None Include="SQL\PSQL\santedb-drop.sql" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Remove="SQL\PSQL\santedb-drop.sql" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SQL\PSQL\santedb-drop.sql">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
