/*
 * Copyright (C) 2021 - 2026, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: fyfej
 * Date: 2024-6-21
 */
using SanteDB.Client.Disconnected.Data.Synchronization;
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Synchronization.ADO.Model
{
    /// <summary>
    /// Represents a synchronization queue registration (name/UUID)
    /// </summary>
    [Table("sync_q_systbl")]
    public class DbSynchronizationQueue
    {

        /// <summary>
        /// Gets or sets the primary key / unique ID of the queue
        /// </summary>
        [Column("q_id"), PrimaryKey, NotNull, AutoGenerated]
        public Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the queue name
        /// </summary>
        [Column("q_name"), NotNull]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the synchronization pattern
        /// </summary>
        [Column("q_pat"), NotNull]
        public SynchronizationPattern Type { get; set; }
    }
}
