using SanteDB.Client.Disconnected.Data.Synchronization;
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Synchronization.ADO.Model
{
    /// <summary>
    /// Represents a synchronization queue registration (name/UUID)
    /// </summary>
    [Table("sync_q_systbl")]
    public class DbSynchronizationQueue 
    {

        /// <summary>
        /// Gets or sets the primary key / unique ID of the queue
        /// </summary>
        [Column("q_id"), PrimaryKey, NotNull, AutoGenerated]
        public Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the queue name
        /// </summary>
        [Column("q_name"), NotNull]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the synchronization pattern
        /// </summary>
        [Column("q_pat"), NotNull]
        public SynchronizationPattern Type { get; set; }
    }
}
