/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230419-01" name="Update:20230419-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="sqlite">
 *	<summary>Update: Adds BI metadata tables to database</summary>
 *	<isInstalled>select count(*) > 0 from patch_db_systbl WHERE PATCH_ID = '20230419-01'</isInstalled>
 * </feature>
 */
 
  CREATE TABLE JOB_STAT_SYSTBL
 (
	JOB_ST_ID BLOB(16) DEFAULT (RANDOMBLOB(16)) NOT NULL,
	JOB_ID BLOB(16) NOT NULL,
	STAT INT NOT NULL,
	LAST_START_UTC BIGINT,
	LAST_STOP_UTC BIGINT,
	CONSTRAINT PK_JOB_STAT_SYSTBL PRIMARY KEY (JOB_ST_ID)
);

CREATE TABLE JOB_SCH_SYSTBL 
(
	JOB_SCH_ID BLOB(16) DEFAULT (RANDOMBLOB(16)) NOT NULL,
	JOB_ID BLOB(16) NOT NULL,
	TYP INT NOT NULL,
	IVL VARCHAR(32),
	START_UTC BIGINT NOT NULL,
	STOP_UTC BIGINT,
	DOW BYTEA,
	CONSTRAINT PK_JOB_SCH_ID PRIMARY KEY (JOB_SCH_ID)
);

CREATE TABLE BI_DEF_SYSTBL 
(
	BI_ID BLOB(16) DEFAULT (RANDOMBLOB(16)) NOT NULL,
	TYP VARCHAR(256) NOT NULL,
	PUB_ID VARCHAR(256) NOT NULL,
	CONSTRAINT PK_BI_DEF_SYSTBL PRIMARY KEY (BI_ID)
);

CREATE UNIQUE INDEX BI_DEF_PUB_ID_UQ_IDX ON BI_DEF_SYSTBL(PUB_ID);

CREATE TABLE BI_DEF_VRSN_SYSTBL 
(
	BI_ID BLOB(16) NOT NULL,
	VRSN_ID BLOB(16) DEFAULT (RANDOMBLOB(16)) NOT NULL,
	VRSN_SEQ_ID BIGINT UNIQUE,
	RPLC_VRSN_ID BLOB(16),
	HEAD BOOLEAN DEFAULT 1 NOT NULL,
	CRT_PROV_ID BLOB(16) NOT NULL,
	CRT_UTC BIGINT DEFAULT (UNIXEPOCH()) NOT NULL,
	OBSLT_PROV_ID BLOB(16),
	OBSLT_UTC BIGINT,
	STS INTEGER NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	DEF BLOB NOT NULL,
	CONSTRAINT PK_BI_DEF_VRSN_SYSTBL PRIMARY KEY (VRSN_ID),
	CONSTRAINT FK_BI_DEF_VRSN_BI_DEF FOREIGN KEY (BI_ID) REFERENCES BI_DEF_SYSTBL(BI_ID),
	CONSTRAINT FK_BI_DEF_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_BI_DEF_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_BI_DEF_VRSN_RPLC_ID FOREIGN KEY (RPLC_VRSN_ID) REFERENCES BI_DEF_VRSN_SYSTBL(VRSN_ID)
);


-- HACK FOR SQLITE
CREATE TRIGGER TRG_BI_DEF_VRSN_AU AFTER INSERT ON BI_DEF_VRSN_SYSTBL
	FOR EACH ROW 
	WHEN NEW.VRSN_SEQ_ID IS NULL	BEGIN
		UPDATE BI_DEF_VRSN_SYSTBL SET VRSN_SEQ_ID = ROWID WHERE BI_DEF_VRSN_SYSTBL.VRSN_ID = NEW.VRSN_ID;
	END;


CREATE TABLE MATCH_CNF_SYSTBL
(
	MATCH_ID BLOB(16) DEFAULT (RANDOMBLOB(16)) NOT NULL,
	PUB_ID VARCHAR(128) NOT NULL,
	CONSTRAINT PK_MATCH_CNF PRIMARY KEY (MATCH_ID)
);

CREATE UNIQUE INDEX MATCH_CNF_PUB_ID_UQ_IDX ON MATCH_CNF_SYSTBL(PUB_ID);

CREATE TABLE MATCH_CNF_VRSN_SYSTBL
(
	MATCH_ID BLOB(16) NOT NULL,
	VRSN_ID BLOB(16) DEFAULT(RANDOMBLOB(16)) NOT NULL,
	VRSN_SEQ_ID INTEGER UNIQUE,
	RPLC_VRSN_ID BLOG(16),
	HEAD BOOLEAN DEFAULT 1 NOT NULL,
	CRT_PROV_ID BLOB(16) NOT NULL,
	CRT_UTC BIGINT DEFAULT (UNIXEPOCH()) NOT NULL,
	OBSLT_PROV_ID BLOB(16),
	OBSLT_UTC BIGINT,
	TRG_TYP VARCHAR(256) NOT NULL,
	STS INTEGER NOT NULL,
	DEF BLOB NOT NULL,
	CONSTRAINT PK_MATCH_CNF_VRSN_SYSTBL PRIMARY KEY (VRSN_ID),
	CONSTRAINT FK_MATCH_CNF_VRSN_BI_DEF FOREIGN KEY (MATCH_ID) REFERENCES MATCH_CNF_SYSTBL(MATCH_ID),
	CONSTRAINT FK_MATCH_CNF_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_MATCH_CNF_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_MATCH_CNF_VRSN_RPLC_ID FOREIGN KEY (RPLC_VRSN_ID) REFERENCES MATCH_CNF_VRSN_SYSTBL(VRSN_ID)
);


-- HACK FOR SQLITE
CREATE TRIGGER TRG_MATCH_CNF_VRSN_AU AFTER INSERT ON MATCH_CNF_VRSN_SYSTBL
	FOR EACH ROW 
	WHEN NEW.VRSN_SEQ_ID IS NULL	BEGIN
		UPDATE MATCH_CNF_VRSN_SYSTBL SET VRSN_SEQ_ID = ROWID WHERE MATCH_CNF_VRSN_SYSTBL.VRSN_ID = NEW.VRSN_ID;
	END;


INSERT INTO PATCH_DB_SYSTBL (PATCH_ID, APPLY_DATE, INFO_NAME) VALUES ('20230419-01', UNIXEPOCH(), 'Add BI metadata configuration tables'); 