/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230330-01" name="Update:20230330-01"   invariantName="sqlite">
 *	<summary>Update: Adds concept set references to the database</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE tbl_name = 'CD_SET_COMP_ASSOC_TBL' AND sql LIKE '%SET_ID%')</isInstalled>
 * </feature>
 */
 
DROP TABLE SEC_SES_TBL ;--#!
 
-- SECURITY SESSIONS TABLE
CREATE TABLE SEC_SES_TBL (
	SES_ID BLOB(16) DEFAULT (randomblob(16)) NOT NULL,
	CRT_UTC BIGINT DEFAULT (unixepoch()) NOT NULL , -- THE TIME WHEN THE SESSION WAS ESTABLISHED
	EXP_UTC BIGINT NOT NULL, -- THE TIME WHEN THE SESSION WILL EXPIRE
	APP_ID BLOB(16) NOT NULL, -- THE SECURITY APPLICATION WHICH THE SESSION IS ESTABLISHED FOR
	USR_ID BLOB(16), -- THE USER IDENTIFIER (APPLICATION USER IF APPLICATION GRANT)
	DEV_ID BLOB(16), -- THE DEVICE IDENTIFIER
	RFRSH_TKN VARCHAR(128) UNIQUE, -- THE REFRESH TOKEN FOR THE OBJECT 
	RFRSH_EXP_UTC BIGINT, -- THE TIME THAT THE REFRESH TOKEN EXPIRES
	AUD VARCHAR(128) NOT NULL, -- THE REMOTE IP ADDRESS THAT ESTABLISHED THE SESSION
	CONSTRAINT PK_SEC_SES_TBL PRIMARY KEY (SES_ID),
	CONSTRAINT FK_SEC_SES_APP_ID FOREIGN KEY (APP_ID) REFERENCES SEC_APP_TBL(APP_ID),
	CONSTRAINT FK_SEC_SES_USR_ID FOREIGN KEY (USR_ID) REFERENCES SEC_USR_TBL(USR_ID),
	CONSTRAINT FK_SEC_SES_DEV_ID FOREIGN KEY (DEV_ID) REFERENCES SEC_DEV_TBL(DEV_ID),
	CONSTRAINT CK_SEC_SES_EXP CHECK (EXP_UTC >= CRT_UTC),
	CONSTRAINT CK_SEC_SES_RFRSH_EXP CHECK (RFRSH_EXP_UTC IS NULL OR RFRSH_EXP_UTC >= EXP_UTC)
);--#!

 CREATE TABLE CD_SET_COMP_ASSOC_TBL (
	SET_COMP_ID BLOB(16) NOT NULL DEFAULT (randomblob(16)),
	SET_ID BLOB(16) NOT NULL,
	TRG_SET_ID BLOB(16) NOT NULL,
	ROL_CS INT NOT NULL CHECK(ROL_CS IN (1,2)),
	CONSTRAINT PK_CD_SET_COMP_ASSOC_TBL PRIMARY KEY (SET_COMP_ID),
	CONSTRAINT FK_CD_SET_COMP_ASSOC_SRC_SET_TBL FOREIGN KEY (SET_ID) REFERENCES CD_SET_TBL(SET_ID),
	CONSTRAINT FK_CD_SET_COMP_ASSOC_TRG_SET_TBL FOREIGN KEY (TRG_SET_ID) REFERENCES CD_SET_TBL(SET_ID)
);--#!
