/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230411-01" name="Update:20230411-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="sqlite">
 *	<summary>Update: Removes needless identifier type table</summary>
 *	<isInstalled>select count(*) > 0 from patch_db_systbl WHERE PATCH_ID = '20230411-01'</isInstalled>
 * </feature>
 */

ALTER TABLE ENT_ID_TBL ADD TYP_CD_ID BLOB(16);
ALTER TABLE ACT_ID_TBL ADD TYP_CD_ID BLOB(16);
-- CONVERT TO CODES
UPDATE ENT_ID_TBL SET TYP_CD_ID = ID_TYP_TBL.TYP_CD_ID FROM ID_TYP_TBL WHERE ENT_ID_TBL.ID_TYP_ID = ID_TYP_TBL.ID_TYP_ID;
UPDATE ACT_ID_TBL SET TYP_CD_ID = ID_TYP_TBL.TYP_CD_ID FROM ID_TYP_TBL WHERE ACT_ID_TBL.ID_TYP_ID = ID_TYP_TBL.ID_TYP_ID;


 -- Drop foreign key FK_ACT_ID_ID_TYP_ID
CREATE TEMPORARY TABLE tmp_act_id_tbl AS
SELECT *
FROM ACT_ID_TBL;

DROP TABLE ACT_ID_TBL;

CREATE TABLE ACT_ID_TBL (
	ACT_ID_ID BLOB(16) DEFAULT (randomblob(16)) NOT NULL,
	TYP_CD_ID BLOB(16),
	ACT_ID BLOB NOT NULL,
	EFFT_VRSN_SEQ_ID INTEGER NOT NULL,
	OBSLT_VRSN_SEQ_ID INTEGER,
	DMN_ID BLOB(16) NOT NULL,
	ID_VAL VARCHAR NOT NULL,
	ISS_DT BIGINT,
	EXP_DT BIGINT,
	CHK_DGT VARCHAR,
	REL INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT PK_ACT_ID_TBL PRIMARY KEY (ACT_ID_ID),
	CONSTRAINT FK_ACT_ID_ACT_ID FOREIGN KEY (ACT_ID) REFERENCES ACT_TBL(ACT_ID),
	CONSTRAINT FK_ACT_ID_TYP_CD_ID FOREIGN KEY (TYP_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_ACT_ID_DMN_ID FOREIGN KEY (DMN_ID) REFERENCES ID_DMN_TBL(DMN_ID),
	CONSTRAINT FK_ACT_ID_EFFT_VRSN_SEQ_ID FOREIGN KEY (EFFT_VRSN_SEQ_ID) REFERENCES ACT_VRSN_TBL(VRSN_SEQ_ID),
	CONSTRAINT FK_ACT_ID_OBSLT_VRSN_SEQ_ID FOREIGN KEY (OBSLT_VRSN_SEQ_ID) REFERENCES ACT_VRSN_TBL(VRSN_SEQ_ID)
);
CREATE INDEX ACT_ID_ACT_ID_IDX ON ACT_ID_TBL (ACT_ID);
CREATE INDEX ACT_ID_VRSN_IDX ON ACT_ID_TBL (EFFT_VRSN_SEQ_ID,OBSLT_VRSN_SEQ_ID);

INSERT INTO ACT_ID_TBL (ACT_ID_ID, TYP_CD_ID, ACT_ID, EFFT_VRSN_SEQ_ID, OBSLT_VRSN_SEQ_ID, DMN_ID, ID_VAL, ISS_DT, EXP_DT, CHK_DGT, REL)
SELECT ACT_ID_ID, TYP_CD_ID, ACT_ID, EFFT_VRSN_SEQ_ID, OBSLT_VRSN_SEQ_ID, DMN_ID, ID_VAL, ISS_DT, EXP_DT, CHK_DGT, REL
FROM tmp_act_id_tbl;

DROP TABLE tmp_act_id_tbl;

 -- Drop foreign key FK_ENT_ID_ID_TYP_ID
CREATE TEMPORARY TABLE tmp_ent_id_tbl AS
SELECT *
FROM ENT_ID_TBL;

DROP TABLE ENT_ID_TBL;

 -- Drop foreign key FK_ENT_ID_ID_TYP_ID
CREATE TABLE ENT_ID_TBL (
	ENT_ID_ID BLOB(16) DEFAULT (randomblob(16)) NOT NULL,
	TYP_CD_ID BLOB(16),
	ENT_ID BLOB NOT NULL,
	EFFT_VRSN_SEQ_ID INTEGER NOT NULL,
	OBSLT_VRSN_SEQ_ID INTEGER,
	DMN_ID BLOB(16) NOT NULL,
	ID_VAL VARCHAR NOT NULL,
	ISS_DT BIGINT,
	EXP_DT BIGINT,
	CHK_DGT VARCHAR,
	REL INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT PK_ENT_ID_TBL PRIMARY KEY (ENT_ID_ID),
	CONSTRAINT FK_ENT_ID_ENT_ID FOREIGN KEY (ENT_ID) REFERENCES ENT_TBL(ENT_ID),
	CONSTRAINT FK_ENT_ID_DMN_ID FOREIGN KEY (DMN_ID) REFERENCES ID_DMN_TBL(DMN_ID),
	CONSTRAINT FK_ENT_ID_TYP_CD_ID FOREIGN KEY (TYP_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_ENT_ID_EFFT_VRSN_SEQ_ID FOREIGN KEY (EFFT_VRSN_SEQ_ID) REFERENCES ENT_VRSN_TBL(VRSN_SEQ_ID),
	CONSTRAINT FK_ENT_ID_OBSLT_VRSN_SEQ_ID FOREIGN KEY (OBSLT_VRSN_SEQ_ID) REFERENCES ENT_VRSN_TBL(VRSN_SEQ_ID)
);
CREATE INDEX ENT_ID_ACT_ID_IDX ON ENT_ID_TBL (ENT_ID);
CREATE INDEX ENT_ID_VRSN_IDX ON ENT_ID_TBL (EFFT_VRSN_SEQ_ID,OBSLT_VRSN_SEQ_ID);

INSERT INTO ENT_ID_TBL (ENT_ID_ID, TYP_CD_ID, ENT_ID, EFFT_VRSN_SEQ_ID, OBSLT_VRSN_SEQ_ID, DMN_ID, ID_VAL, ISS_DT, EXP_DT, CHK_DGT, REL)
SELECT ENT_ID_ID, TYP_CD_ID, ENT_ID, EFFT_VRSN_SEQ_ID, OBSLT_VRSN_SEQ_ID, DMN_ID, ID_VAL, ISS_DT, EXP_DT, CHK_DGT, REL
FROM tmp_ent_id_tbl;

DROP TABLE tmp_ent_id_tbl;

-- DROP THE TABLE
DROP TABLE ID_TYP_TBL;

INSERT INTO PATCH_DB_SYSTBL (PATCH_ID, APPLY_DATE, INFO_NAME) VALUES ('20230411-01', UNIXEPOCH(), 'REMOVE NEEDLESS ID TYPE TABLE'); 