/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230118" name="Update:Cumulative Update for SQLite" applyRange="0.2.0.0-0.9.0.0" invariantName="sqlite">
 *	<summary>Update:Migrate person ctable columns</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE tbl_name = 'PSN_TBL' AND sql LIKE '%DCSD_UTC%')</isInstalled>
 * </feature>
 */
 -- OPTIONAL
ALTER TABLE PSN_TBL ADD VIP_STS_CD_ID BLOB(16);--#!
 -- OPTIONAL
ALTER TABLE PSN_TBL ADD NAT_CD_ID BLOB(16);--#!
ALTER TABLE PSN_TBL ADD DCSD_UTC INTEGER;--#!
ALTER TABLE PSN_TBL ADD DCSD_PREC CHAR(1) CHECK (DCSD_PREC IN ('Y','m','D'));--#!
UPDATE CD_VRSN_TBL SET MNEMONIC = 'DataEnterer' WHERE CD_ID = X'D2660DC5DAE5344AB2B74CD4FE4EF2C4';
ALTER TABLE PSN_TBL ADD DOB_PREC_NEW CHAR(1) CHECK (DOB_PREC_NEW IN ('Y','m','D'));
UPDATE PSN_TBL SET DOB_PREC_NEW = CASE WHEN DOB_PREC = 'M' THEN 'm' ELSE DOB_PREC END;
ALTER TABLE PSN_TBL DROP DOB_PREC;
ALTER TABLE PSN_TBL RENAME COLUMN DOB_PREC_NEW TO DOB_PREC;

UPDATE PSN_TBL SET 
	VIP_STS_CD_ID = PAT_TBL.VIP_STS_CD_ID , 
	NAT_CD_ID = PAT_TBL.NAT_CD_ID,
	DCSD_UTC = PAT_TBL.DCSD_UTC,
	DCSD_PREC = PAT_TBL.DCSD_PREC
	FROM PAT_TBL WHERE PSN_TBL.ENT_VRSN_ID = PAT_TBL.ENT_VRSN_ID ; 


CREATE TABLE PAT_TBL_NEW
(
	ENT_VRSN_ID BLOB(16) NOT NULL, -- THE VERSION ID OF THE ENTITY VERSION TO WHICH THE PATIENT INFO APPLIES
	MB_ORD INTEGER, -- THE ORDER IN WHICH THE PATIENT WAS BORN
	MRTL_STS_CD_ID BLOB(16), -- MARITAL STATUS KEY
	EDU_LVL_CD_ID BLOB(16), -- EDUCATION LEVEL KEY
	LVN_ARG_CD_ID BLOB(16), -- LIVING ARRANGEMENT
	RLGN_CD_ID BLOB(16), -- RELIGION CODE
	ETH_GRP_CD_ID BLOB(16), -- ETHNIC GROUP KEY
	CONSTRAINT PK_PAT_TBL PRIMARY KEY (ENT_VRSN_ID),
	CONSTRAINT FK_PAT_ENT_VRSN_ID FOREIGN KEY (ENT_VRSN_ID) REFERENCES PSN_TBL(ENT_VRSN_ID),
	CONSTRAINT FK_PSN_MRTL_STS_CD_ID FOREIGN KEY (MRTL_STS_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PAT_EDU_LVL_CD_ID FOREIGN KEY (EDU_LVL_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PAT_LVN_ARG_CD_ID FOREIGN KEY (LVN_ARG_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PAT_RLGN_CD_ID FOREIGN KEY (RLGN_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PAT_EHT_GRP_CD_ID FOREIGN KEY (ETH_GRP_CD_ID) REFERENCES CD_TBL(CD_ID)
);

INSERT INTO PAT_TBL_NEW SELECT ENT_VRSN_ID, MB_ORD, MRTL_STS_CD_ID, EDU_LVL_CD_ID, LVN_ARG_CD_ID, RLGN_CD_ID, ETH_GRP_CD_ID FROM PAT_TBL;
DROP TABLE PAT_TBL;
ALTER TABLE PAT_TBL_NEW RENAME TO PAT_TBL;

