/** 
 * <feature scope="SanteDB.Persistence.Data" id="20240913" name="Update:20240913"  invariantName="sqlite">
 *	<summary>Update: Registers the care pathway table</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE name='CP_DEF_TBL')</isInstalled>
 * </feature>
 */
 -- OPTIONAL
 ALTER TABLE CP_TBL DROP COLUMN PROG; 
 --#!

 CREATE TABLE CP_DEF_TBL (
	PTH_ID BLOB(16) DEFAULT (RANDOMBLOB()) NOT NULL, 
	MNEMONIC VARCHAR(128) NOT NULL UNIQUE, 
	DESCR TEXT,
	ENROL INT,
	ELIG TEXT,
	TPL_ID BLOB(16), 
	CRT_PROV_ID BLOB(16) NOT NULL,
	CRT_UTC BIGINT DEFAULT (unixepoch()) NOT NULL,
	UPD_PROV_ID BLOB(16),
	UPD_UTC BIGINT,
	OBSLT_PROV_ID BLOB(16),
	OBSLT_UTC BIGINT,
	CONSTRAINT PK_CP_DEF_TBL PRIMARY KEY (PTH_ID),
	CONSTRAINT FK_CP_DEF_TPL_ID FOREIGN KEY (TPL_ID) REFERENCES TPL_DEF_TBL(TPL_ID),
	CONSTRAINT FK_CP_DEF_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_CP_DEF_UPD_PROV_ID FOREIGN KEY (UPD_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_CP_DEF_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID)
 );

 -- OPTIONAL
 ALTER TABLE CP_TBL ADD PTH_ID BLOB(16);
 --#!
 

