/** 
 * <feature scope="SanteDB.Persistence.Data" id="20240120" name="Update:Adds relationship validation to only server"  environment="Server" invariantName="sqlite">
 *	<summary>Update:Add relationship validation for server environment</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE name='ENT_REL_VRFY_TRG')</isInstalled>
 * </feature>
 */

CREATE TRIGGER ENT_REL_VRFY_TRG 
	BEFORE
INSERT
	ON
	ENT_REL_TBL 
	FOR EACH ROW
BEGIN
	SELECT
		RAISE(ABORT, 'ENTITY RELATIONSHIP FAILED VALIDATION')
	WHERE
		NOT EXISTS (
			SELECT
				1
			FROM
				REL_VRFY_SYSTBL
			LEFT JOIN ENT_VRSN_TBL SR ON
				(NEW.SRC_ENT_ID = SR.ENT_ID)
			LEFT JOIN ENT_VRSN_TBL TR ON
				(NEW.TRG_ENT_ID = TR.ENT_ID)
			WHERE
				(SRC_CLS_CD_ID IS NULL OR SR.CLS_CD_ID = SRC_CLS_CD_ID)
				AND (TRG_CLS_CD_ID IS NULL OR TR.CLS_CD_ID = TRG_CLS_CD_ID)
				AND REL_TYP_CD_ID = NEW.REL_TYP_CD_ID
				AND REL_VRFY_SYSTBL.REL_CLS = 1);
END; --#!


CREATE TRIGGER ACT_REL_VRFY_TRG 
	BEFORE
INSERT
	ON
	ACT_REL_TBL 
	FOR EACH ROW
BEGIN
	SELECT
		RAISE(ABORT, 'ACT RELATIONSHIP FAILED VALIDATION')
	WHERE
		NOT EXISTS (
			SELECT
				1
			FROM
				REL_VRFY_SYSTBL
				INNER JOIN ACT_VRSN_TBL SR ON
					(NEW.SRC_ACT_ID = SR.ACT_ID)
				INNER JOIN ACT_VRSN_TBL TR ON
					(NEW.TRG_ACT_ID = TR.ACT_ID)
			WHERE
				(SRC_CLS_CD_ID IS NULL OR SR.CLS_CD_ID = SRC_CLS_CD_ID)
				AND (TRG_CLS_CD_ID IS NULL OR TR.CLS_CD_ID = TRG_CLS_CD_ID)
				AND REL_TYP_CD_ID = NEW.REL_TYP_CD_ID
				AND REL_VRFY_SYSTBL.REL_CLS = 2);
END; --#!


CREATE TRIGGER ACT_PTCPT_VRFY_TRG 
	BEFORE
INSERT
	ON
	ACT_PTCPT_TBL 
	FOR EACH ROW
BEGIN
	SELECT
		RAISE(ABORT, 'ACT PARTICIPATION FAILED VALIDATION')
	WHERE
		NOT EXISTS (
		SELECT
			1
		FROM
			REL_VRFY_SYSTBL
			INNER JOIN ACT_VRSN_TBL SR ON
				(NEW.ACT_ID = SR.ACT_ID)
			INNER JOIN ENT_VRSN_TBL TR ON
				(NEW.ENT_ID = TR.ENT_ID)
		WHERE
			(SRC_CLS_CD_ID IS NULL OR SR.CLS_CD_ID = SRC_CLS_CD_ID)
			AND (TRG_CLS_CD_ID IS NULL OR TR.CLS_CD_ID = TRG_CLS_CD_ID)
			AND REL_TYP_CD_ID = NEW.ROL_CD_ID
			AND REL_VRFY_SYSTBL.REL_CLS = 3);
END;--#!
