/** 
 * <feature scope="SanteDB.Persistence.Data" id="20240104-01" name="Update:20240104-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="sqlite">
 *	<summary>Update: Adds persistence of data quality rules in the primary database</summary>
 *	<isInstalled>select count(*) > 0 from patch_db_systbl WHERE PATCH_ID = '20240104-01'</isInstalled>
 * </feature>
 */
 
 CREATE TABLE DQ_CNF_SYSTBL (
	DQ_ID BLOB(16) DEFAULT (randomblob(16)) NOT NULL,
	ACTIVE INT DEFAULT 1 NOT NULL,
	MNEMONIC VARCHAR(256) NOT NULL, 
	NAME VARCHAR(512) NOT NULL,
	CRT_PROV_ID BLOB NOT NULL,
	CRT_UTC BIGINT DEFAULT(unixepoch()) NOT NULL,
	UPD_PROV_ID BLOB(16),
	UPD_UTC BIGINT,
	OBSLT_PROV_ID BLOB(16),
	OBSLT_UTC BIGINT,
	CONSTRAINT PK_DQ_CNF_SYSTBL PRIMARY KEY (DQ_ID),
	CONSTRAINT FK_DQ_CRT_PROV_TBL FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_DQ_UPD_PROV_TBL FOREIGN KEY (UPD_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_DQ_OBSLT_PROV_TBL FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT CK_OBSLT_PROV_LOGIC CHECK ((OBSLT_PROV_ID IS NULL AND OBSLT_UTC IS NULL) OR (OBSLT_PROV_ID IS NOT NULL AND OBSLT_UTC IS NOT NULL))
 );

 CREATE UNIQUE INDEX DQ_CNF_MNEMONIC_UQ_IDX ON DQ_CNF_SYSTBL(MNEMONIC) WHERE (OBSLT_UTC IS NULL);

 CREATE TABLE DQ_RES_SYSTBL (
	RES_ID BLOB(16) DEFAULT (randomblob(16)) NOT NULL,
	DQ_ID BLOB(16) NOT NULL,
	RES VARCHAR(128) NOT NULL,
	CONSTRAINT PK_DQ_RES_SYSTBL PRIMARY KEY (RES_ID),
	CONSTRAINT FK_DQ_RES_CNF_SYSTBL FOREIGN KEY (DQ_ID) REFERENCES DQ_CNF_SYSTBL(DQ_ID)
);

CREATE TABLE DQ_RES_ASRT_SYSTBL (
	ASRT_ID BLOB(16) DEFAULT (randomblob(16)) NOT NULL,
	RES_ID BLOB(16) NOT NULL,
	MNEMONIC VARCHAR(256) NOT NULL UNIQUE,
	TXT TEXT NOT NULL,
	PRI INT NOT NULL DEFAULT 4,
	EVAL INT NOT NULL DEFAULT 0,
	EXPR TEXT NOT NULL,
	CONSTRAINT PK_REQ_ASRT_SYSTBL PRIMARY KEY (ASRT_ID),
	CONSTRAINT FK_RES_ASRT_RES_SYSTBL FOREIGN KEY (RES_ID) REFERENCES DQ_RES_SYSTBL(RES_ID)
);

CREATE INDEX DQ_REQ_ASRT_RES_IDX ON DQ_REQ_ASRT_SYSTBL(RES_ID);

INSERT INTO PATCH_DB_SYSTBL (PATCH_ID, APPLY_DATE, INFO_NAME) VALUES ('20240104-01', UNIXEPOCH(), 'Adds DQ storage tables to database'); 
