/** 
 * <feature scope="SanteDB.Persistence.Data" id="20250530" name="Update:20250530"  invariantName="sqlite" environment="Client">
 *	<summary>Update: Remove Client Triggers</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'Trigger')</isInstalled>
 * </feature>
 */
 
DROP TRIGGER IF EXISTS TRG_CD_VRSN_AU;
DROP TRIGGER IF EXISTS TRG_ACT_VRSN_AU;
DROP TRIGGER IF EXISTS TRG_ENT_VRSN_AU;
DROP TRIGGER IF EXISTS TRG_ADDR_CMP_AU;
DROP TRIGGER IF EXISTS TRG_NAME_CMP_AU;
DROP TRIGGER IF EXISTS TRG_ACT_PTCPT_AU;
DROP TRIGGER IF EXISTS TRG_BI_DEF_VRSN_AU;
DROP TRIGGER IF EXISTS TRG_MATCH_CNF_VRSN_AU;
DROP TRIGGER IF EXISTS TRG_CDSS_LIB_VRSN_TBL_AU;
DROP TRIGGER IF EXISTS TRG_IMS_STK_LDGR_TBL_AI;
DROP TRIGGER IF EXISTS ENT_REL_VRFY_TRG;
DROP TRIGGER IF EXISTS ACT_REL_VRFY_TRG;
DROP TRIGGER IF EXISTS ACT_PTCPT_VRFY_TRG;