/** 
 * <feature scope="SanteDB.Persistence.Data" id="20250831" name="Update:20250831"  invariantName="sqlite">
 *	<summary>Update: Update: Adds the date observation type to the database</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE name='dt_obs_tbl' AND sql LIKE '%val_prec%')</isInstalled>
 * </feature>
 */
 
 DROP TABLE IF EXISTS DT_OBS_TBL;
 
 CREATE TABLE DT_OBS_TBL (
	ACT_VRSN_ID BLOB(16) NOT NULL, -- THE VERSION TO WHICH THE OBSERVATION DTA APPLIES
	VAL_DT BIGINT NULL, -- THE DATE VALUE IN EPOCH TIME
	VAL_PREC CHAR(1) NULL,
	CONSTRAINT PK_DT_OBS_TBL PRIMARY KEY (ACT_VRSN_ID),
	CONSTRAINT FK_DT_OBS_ACT_VRSN_ID FOREIGN KEY (ACT_VRSN_ID) REFERENCES OBS_TBL(ACT_VRSN_ID)
 );
 --#!
 DROP INDEX OBS_VAL_TYP_IDX;
 --#!
 ALTER TABLE OBS_TBL ADD TMP_VAL_TYP VARCHAR(2);
 --#!
 UPDATE OBS_TBL SET TMP_VAL_TYP = VAL_TYP;
 --#!
 ALTER TABLE OBS_TBL DROP VAL_TYP;
 --#!
 ALTER TABLE OBS_TBL ADD VAL_TYP VARCHAR(2) CHECK (VAL_TYP IN ('PQ','ST','TS','CD'));
 --#!
 UPDATE OBS_TBL SET VAL_TYP = TMP_VAL_TYP;
 --#!
 ALTER TABLE OBS_TBL DROP TMP_VAL_TYP;
 --#!
 CREATE INDEX OBS_VAL_TYP_IDX ON OBS_TBL(VAL_TYP);