/** 
 * <feature scope="SanteDB.Persistence.Data" id="20250210" name="Update:20250210"  invariantName="sqlite">
 *	<summary>Update: Adds persistence for concept tags</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE name='CD_TAG_TBL' OR name='cd_tag_tbl')</isInstalled>
 * </feature>
 */
 
CREATE TABLE CD_TAG_TBL (
	TAG_ID blob(16) DEFAULT (randomblob(16)) NOT NULL,
	CD_ID blob(16) NOT NULL,
	TAG_NAME VARCHAR(64) NOT NULL,
	TAG_VALUE TEXT NULL,
	CRT_UTC BIGINT DEFAULT (unixepoch()) NOT NULL,
	CRT_PROV_ID blob(16) NOT NULL,
	OBSLT_UTC BIGINT NULL,
	OBSLT_PROV_ID blob(16) NULL,
	CONSTRAINT CK_CD_TAG_OBSLT_USR CHECK ((((OBSLT_PROV_ID IS NULL) AND (OBSLT_UTC IS NULL)) OR ((OBSLT_PROV_ID IS NOT NULL) AND (OBSLT_UTC IS NOT NULL)))),
	CONSTRAINT PK_CD_TAG_TBL PRIMARY KEY (TAG_ID),
	CONSTRAINT FK_CD_TAG_CD_ID FOREIGN KEY (CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_CD_TAG_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_CD_TAG_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID)
);

CREATE INDEX CD_TAG_CD_ID_IDX ON CD_TAG_TBL(CD_ID);


CREATE TABLE CD_EXT_TBL (
	CD_EXT_ID blob(16) DEFAULT (randomblob(16)) NOT NULL,
	CD_ID blob(16) NOT NULL,
	EXT_TYP_ID blob(16) NOT NULL,
	EXT_VAL BLOB NULL,
	EXT_DISP TEXT NULL,
	EFFT_VRSN_SEQ_ID INTEGER NOT NULL,
	OBSLT_VRSN_SEQ_ID INTEGER NULL,
	CONSTRAINT PK_CD_EXT_TBL PRIMARY KEY (CD_EXT_ID),
	CONSTRAINT FK_CD_EXT_CD_ID FOREIGN KEY (CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_CD_EXT_EXT_TYP_ID FOREIGN KEY (EXT_TYP_ID) REFERENCES EXT_TYP_TBL(EXT_TYP_ID),
	CONSTRAINT FK_CD_EXT_OBSLT_VRSN_SEQ_ID FOREIGN KEY (OBSLT_VRSN_SEQ_ID) REFERENCES CD_VRSN_TBL(VRSN_SEQ_ID),
	CONSTRAINT FK_CD_EXT_TBL_EFFT_VRSN_SEQ_ID FOREIGN KEY (EFFT_VRSN_SEQ_ID) REFERENCES CD_VRSN_TBL(VRSN_SEQ_ID)
);
CREATE INDEX CD_EXT_CD_ID ON CD_EXT_TBL (CD_ID);
CREATE INDEX CD_EXT_VRSN_IDX ON CD_EXT_TBL(EFFT_VRSN_SEQ_ID, OBSLT_VRSN_SEQ_ID);
