/** 
 * <feature scope="SanteDB.Persistence.Data" id="20251203" name="Update:20251203"  invariantName="sqlite">
 *	<summary>Update: Migrates Marital Status to Person</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM patch_db_systbl WHERE patch_id='20251203')</isInstalled>
 * </feature>
 */
 
 DROP VIEW IF EXISTS org_santedb_emr_bi_query_patient_details;

 CREATE TABLE PSN_TBL_NEW (
	ENT_VRSN_ID BLOB NOT NULL,
	DOB INTEGER,
	OCC_CD_ID BLOB(16),
	GNDR_CD_ID BLOB(16),
	VIP_STS_CD_ID BLOB(16),
	NAT_CD_ID BLOB(16),
	DCSD_UTC INTEGER,
	DCSD_PREC CHAR,
	DOB_PREC CHAR,
	MRTL_STS_CD_ID BLOB(16),
	CONSTRAINT PK_PSN_TBL PRIMARY KEY (ENT_VRSN_ID),
	CONSTRAINT FK_PSN_ENT_VRSN_ID FOREIGN KEY (ENT_VRSN_ID) REFERENCES ENT_VRSN_TBL(ENT_VRSN_ID),
	CONSTRAINT FK_PSN_GNDR_CD_ID FOREIGN KEY (GNDR_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PSN_OCC_CD_ID FOREIGN KEY (OCC_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PSN_MRTL_STS_CD_ID FOREIGN KEY (MRTL_STS_CD_ID) REFERENCES CD_TBL(CD_ID)
);

CREATE TABLE PAT_TBL_NEW
(
	ENT_VRSN_ID BLOB(16) NOT NULL, -- THE VERSION ID OF THE ENTITY VERSION TO WHICH THE PATIENT INFO APPLIES
	MB_ORD INTEGER, -- THE ORDER IN WHICH THE PATIENT WAS BORN
	EDU_LVL_CD_ID BLOB(16), -- EDUCATION LEVEL KEY
	LVN_ARG_CD_ID BLOB(16), -- LIVING ARRANGEMENT
	RLGN_CD_ID BLOB(16), -- RELIGION CODE
	ETH_GRP_CD_ID BLOB(16), -- ETHNIC GROUP KEY
	CONSTRAINT PK_PAT_TBL PRIMARY KEY (ENT_VRSN_ID),
	CONSTRAINT FK_PAT_ENT_VRSN_ID FOREIGN KEY (ENT_VRSN_ID) REFERENCES PSN_TBL_NEW(ENT_VRSN_ID),
	CONSTRAINT FK_PAT_EDU_LVL_CD_ID FOREIGN KEY (EDU_LVL_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PAT_LVN_ARG_CD_ID FOREIGN KEY (LVN_ARG_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PAT_RLGN_CD_ID FOREIGN KEY (RLGN_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_PAT_EHT_GRP_CD_ID FOREIGN KEY (ETH_GRP_CD_ID) REFERENCES CD_TBL(CD_ID)
);
	
INSERT INTO PSN_TBL_NEW 
SELECT 
	ENT_VRSN_ID, DOB, OCC_CD_ID, GNDR_CD_ID, VIP_STS_CD_ID, NAT_CD_ID, DCSD_UTC, DCSD_PREC, DOB_PREC, PAT_TBL.MRTL_STS_CD_ID
FROM 
	PSN_TBL 
	INNER JOIN PAT_TBL USING(ENT_VRSN_ID);

INSERT INTO PAT_TBL_NEW 
SELECT 
	ENT_VRSN_ID, MB_ORD, EDU_LVL_CD_ID, LVN_ARG_CD_ID, RLGN_CD_ID, ETH_GRP_CD_ID
FROM PAT_TBL;

DROP TABLE PSN_TBL;
DROP TABLE PAT_TBL;

ALTER TABLE PSN_TBL_NEW RENAME TO PSN_TBL;
ALTER TABLE PAT_TBL_NEW RENAME TO PAT_TBL;

INSERT INTO PATCH_DB_SYSTBL (PATCH_ID, APPLY_DATE, INFO_NAME) VALUES ('20251203', unixepoch(), 'Update: Migrate marital status to person');--#!
