/** 
 * <feature scope="SanteDB.Persistence.Data" id="20241119" name="Update:20241119"  invariantName="sqlite">
 *	<summary>Update: Updates the concept relationship tables to support flow relationships</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE name='BDL_CORR_SYSTBL' OR name='bdl_corr_systbl')</isInstalled>
 * </feature>
 */

 CREATE TABLE BDL_CORR_SYSTBL (
	CORR_ID BLOB(16) NOT NULL,
	CONSTRAINT PK_BDL_CORR_SYSTBL PRIMARY KEY (CORR_ID)
 );

CREATE TABLE BDL_CORR_SUBM_SYSTBL (
	SUBM_ID BLOB(16) NOT NULL, 
	CORR_ID BLOB(16) NOT NULL,
	SEQ BIGINT NOT NULL,
	CRT_PROV_ID BLOB(16) NOT NULL,
	CRT_UTC BIGINT DEFAULT (UNIXEPOCH()) NOT NULL,
	CONSTRAINT PK_BDL_CORR_SUBM_SYSTBL PRIMARY KEY (SUBM_ID),
	CONSTRAINT FK_BDL_CORR_SUBM_CORR_SYSTBL FOREIGN KEY (CORR_ID) REFERENCES BDL_CORR_SYSTBL(CORR_ID),
	CONSTRAINT FK_BDL_CORR_SUBM_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID)
);

CREATE INDEX BDL_CORR_SUBM_CORR_ID_IDX ON BDL_CORR_SUBM_SYSTBL(CORR_ID);