/** 
 * <feature scope="SanteDB.Persistence.Data" id="20251007" name="Update:20251007"  invariantName="sqlite">
 *	<summary>Update: Removes NOT NULL from observation tables</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM patch_db_systbl WHERE patch_id='20251007')</isInstalled>
 * </feature>
 */
 CREATE TABLE CD_OBS_TBL_X (
	ACT_VRSN_ID BLOB(16) NOT NULL, -- THE VERSION TO WHICH THE OBSERVATION DTA APPLIES
	VAL_CD_ID BLOB(16) NULL, 	
	CONSTRAINT PK_CD_OBS_TBL PRIMARY KEY (ACT_VRSN_ID),
	CONSTRAINT FK_CD_OBS_ACT_VRSN_ID FOREIGN KEY (ACT_VRSN_ID) REFERENCES OBS_TBL(ACT_VRSN_ID),
	CONSTRAINT FK_CD_OBS_VAL_CD_ID FOREIGN KEY (VAL_CD_ID) REFERENCES CD_TBL(CD_ID)
);

INSERT INTO CD_OBS_TBL_X (ACT_VRSN_ID, VAL_CD_ID) SELECT ACT_VRSN_ID, VAL_CD_ID FROM CD_OBS_TBL;

DROP TABLE CD_OBS_TBL;

ALTER TABLE CD_OBS_TBL_X RENAME TO CD_OBS_TBL;


CREATE TABLE QTY_OBS_TBL_X (
	ACT_VRSN_ID BLOB(16) NOT NULL, -- THE VERSION TO WHICH THE OBSERVATION DATA APLIES
	QTY DECIMAL NULL, -- THE QUANTITY ITSELF
	QTY_PRC NUMERIC(2), -- THE PRECISION OF THE OBSERVED VALUES
	UOM_CD_ID BLOB(16) NOT NULL, -- THE UNIT OF MEASURE OF THE QUANTITY
	CONSTRAINT PK_QTY_OBS_TBL PRIMARY KEY (ACT_VRSN_ID),
	CONSTRAINT FK_QTY_OBS_ACT_VRSN_ID FOREIGN KEY (ACT_VRSN_ID) REFERENCES OBS_TBL(ACT_VRSN_ID),
	CONSTRAINT FK_QTY_OBS_UOM_CD_ID FOREIGN KEY (UOM_CD_ID) REFERENCES CD_TBL(CD_ID)
);

INSERT INTO QTY_OBS_TBL_X (ACT_VRSN_ID, QTY, QTY_PRC, UOM_CD_ID) SELECT ACT_VRSN_ID, QTY, QTY_PRC, UOM_CD_ID FROM QTY_OBS_TBL;

DROP TABLE QTY_OBS_TBL;

ALTER TABLE QTY_OBS_TBL_X RENAME TO QTY_OBS_TBL;


CREATE TABLE TXT_OBS_TBL_X (
	ACT_VRSN_ID BLOB(16) NOT NULL, -- THE VERSION TO WHICH THE BLOB SUB_TYPE TEXT DATA APPLIES
	OBS_VAL BLOB SUB_TYPE TEXT NULL, -- THE OBSERVATION VALUE 
	CONSTRAINT PK_TXT_OBS_TBL PRIMARY KEY (ACT_VRSN_ID),
	CONSTRAINT FK_TXT_OBS_ACT_VRSN_ID FOREIGN KEY (ACT_VRSN_ID) REFERENCES OBS_TBL(ACT_VRSN_ID)
);

INSERT INTO TXT_OBS_TBL_X (ACT_VRSN_ID, OBS_VAL) SELECT ACT_VRSN_ID, OBS_VAL FROM TXT_OBS_TBL;

DROP TABLE TXT_OBS_TBL;

ALTER TABLE TXT_OBS_TBL_X RENAME TO TXT_OBS_TBL;

INSERT INTO PATCH_DB_SYSTBL (PATCH_ID, APPLY_DATE, INFO_NAME) VALUES ('20251007', unixepoch(), 'Update: Removes NOT NULL from observation tables');--#!
