/** 
 * <feature scope="SanteDB.Persistence.Data" id="20260308-02" name="Update:20260308-02"   invariantName="sqlite" >
 *	<summary>Update: Refactor the mail message tables</summary>
 *  <isInstalled>SELECT EXISTS (SELECT 1 FROM patch_db_systbl WHERE patch_id='20260308-02')</isInstalled>
 * </feature>
 */
 
DROP TABLE MAIL_BOX_MSG_ASSOC_TBL; 
 DROP TABLE  MAIL_BOX_TBL;
 DROP TABLE MAIL_MSG_RCPT_TO_TBL;
 DROP TABLE MAIL_MSG_TBL;

 CREATE TABLE MAIL_MSG_TBL (
	MAIL_MSG_ID BLOB(16) NOT NULL DEFAULT (RANDOMBLOB(16)),
	CRT_UTC TIMESTAMPTZ DEFAULT (UNIXEPOCH()) NOT NULL,
	CRT_PROV_ID UUID NOT NULL,
	OBSLT_UTC TIMESTAMPTZ NULL,
	OBSLT_PROV_ID UUID NULL,
	FRM BLOB(16) NOT NULL,
	FRM_TXT VARCHAR(256) NOT NULL,
	TO_TXT VARCHAR(1024) NOT NULL,
	FLAGS INT DEFAULT 0 NOT NULL,
	SUBJ VARCHAR(256) NOT NULL,
	BODY TEXT NOT NULL,
	CONSTRAINT PK_MAIL_MSG_TBL PRIMARY KEY (MAIL_MSG_ID),
	CONSTRAINT FK_MAIL_MSG_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_MAIL_MSG_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT CK_MAIL_OBSLT_UTC CHECK (OBSLT_UTC IS NULL AND OBSLT_PROV_ID IS NULL OR OBSLT_UTC IS NOT NULL AND OBSLT_PROV_ID IS NOT NULL)
);

CREATE TABLE MAIL_BOX_TBL (
	MAIL_BOX_ID BLOB(16) NOT NULL DEFAULT (RANDOMBLOB(16)),
	OWN_ID BLOB(16) NOT NULL, 
	NAME VARCHAR(32) NOT NULL,
	CRT_UTC BIGINT DEFAULT (UNIXEPOCH()) NOT NULL,
	CRT_PROV_ID BLOB(16) NOT NULL,
	OBSLT_UTC BIGINT NULL,
	OBSLT_PROV_ID BLOB(16) NULL,
	CONSTRAINT PK_MAIL_BOX_TBL PRIMARY KEY (MAIL_BOX_ID),
	CONSTRAINT FK_MAIL_BOX_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_MAIL_BOX_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID)
);

CREATE UNIQUE INDEX IX_MAIL_BOX_OWNER_NAME_UQ ON MAIL_BOX_TBL(OWN_ID, NAME) WHERE (OBSLT_UTC IS NULL);
CREATE INDEX IX_MAIL_BOX_OWNER ON MAIL_BOX_TBL(OWN_ID);

CREATE TABLE MAIL_MSG_RCPT_TO_TBL (
	MAIL_MSG_ID BLOB(16) NOT NULL,
	RCPT_ID BLOB(16) NOT NULL,
	CONSTRAINT PK_MAIL_MSG_RCPT_TO_TBL PRIMARY KEY (MAIL_MSG_ID, RCPT_ID),
	CONSTRAINT FK_MAIL_MSG_RCPT_TO_MAIL_ID FOREIGN KEY (MAIL_MSG_ID) REFERENCES MAIL_MSG_TBL(MAIL_MSG_ID)
);

CREATE INDEX IX_MAIL_MSG_RCPT_TO_MSG ON MAIL_MSG_RCPT_TO_TBL (MAIL_MSG_ID);

CREATE TABLE MAIL_BOX_MSG_ASSOC_TBL (
	MAIL_BOX_MSG_ID BLOB(16) NOT NULL DEFAULT (RANDOMBLOB(16)),
	MAIL_BOX_ID BLOB(16) NOT NULL,
	MAIL_MSG_ID BLOB(16) NOT NULL,
	STS INT NOT NULL DEFAULT 0,
	MSG_UTC BIGINT DEFAULT (UNIXEPOCH()) NOT NULL,
	CRT_UTC BIGINT DEFAULT (UNIXEPOCH()) NOT NULL,
	CONSTRAINT PK_MAIL_BOX_MSG_ASSOC_TBL PRIMARY KEY (MAIL_BOX_MSG_ID),
	CONSTRAINT FK_MAIL_BOX_MSG_ASSOC_MAIL_BOX_TBL FOREIGN KEY (MAIL_BOX_ID) REFERENCES MAIL_BOX_TBL(MAIL_BOX_ID),
	CONSTRAINT FK_MAIL_BOX_MSG_ASSOC_MAIL_MSG_TBL FOREIGN KEY (MAIL_MSG_ID) REFERENCES MAIL_MSG_TBL(MAIL_MSG_ID)
);

CREATE INDEX IX_MAIL_BOX_MSG_ASSOC_MAIL_BOX ON MAIL_BOX_MSG_ASSOC_TBL(MAIL_BOX_ID);
CREATE UNIQUE INDEX uq_ix_mail_box_msg_assoc_mail_box ON mail_box_msg_assoc_tbl(mail_box_id, mail_msg_id);

INSERT OR IGNORE INTO mail_box_tbl (own_id, name, crt_prov_id)
SELECT usr_id, 'Inbox', x'76A0DCFA90366E4AAF9EF1CD68E8C7E8'
FROM sec_usr_tbl
WHERE usr_name NOT IN ('SYSTEM','ANONYMOUS');
INSERT OR IGNORE INTO mail_box_tbl (own_id, name, crt_prov_id)
SELECT usr_id, 'Deleted', x'76A0DCFA90366E4AAF9EF1CD68E8C7E8'
FROM sec_usr_tbl
WHERE usr_name NOT IN ('SYSTEM','ANONYMOUS');
INSERT OR IGNORE INTO mail_box_tbl (own_id, name, crt_prov_id)
SELECT usr_id, 'Sent', x'76A0DCFA90366E4AAF9EF1CD68E8C7E8'
FROM sec_usr_tbl
WHERE usr_name NOT IN ('SYSTEM','ANONYMOUS');
INSERT OR IGNORE INTO mail_box_tbl (own_id, name, crt_prov_id)
SELECT dev_id, 'Inbox', x'76A0DCFA90366E4AAF9EF1CD68E8C7E8'
FROM sec_dev_tbl
WHERE dev_pub_id NOT IN ('SYSTEM','ANONYMOUS');

INSERT INTO PATCH_DB_SYSTBL (PATCH_ID, APPLY_DATE, INFO_NAME) VALUES ('20260308-02', UNIXEPOCH(), 'UPDATE: ADD TIME BOUNDS TO PROTOCOL');--#!
