/** 
 * <feature scope="SanteDB.Persistence.Data" id="20221130-01" name="Update:20221130-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="npgsql">
 *	<summary>Update: Add foreign data manager tables</summary>
 *	<isInstalled>select ck_patch('20221130-01')</isInstalled>
 * </feature>
 */


  CREATE TABLE FD_STG_SYSTBL (
	FD_ID UUID NOT NULL DEFAULT (uuid_generate_v1()), -- UNIQUE IDENTIFIER FOR THE FOREIGN DATA IMPORT
	CRT_UTC TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- CREATION TIME
	CRT_PROV_ID UUID, -- CREATION USER
	OBSLT_UTC TIMESTAMPTZ, -- OBSOLETION TIME
	OBSLT_PROV_ID UUID, -- OBSOLETION USER
	UPD_UTC TIMESTAMPTZ, -- UPDATE USER
	UPD_PROV_ID UUID, -- UPDATED TIME
	NAME VARCHAR(128) NOT NULL, -- NAME OF THE ORIGINAL FILE / IMPORT STAGED
	STS_CS INTEGER NOT NULL DEFAULT 0, -- STATUS CODE OF THE IMPORT
	FD_MAP_ID UUID, -- FOREIGN DATA MAP TO USE
	SRC_STR_ID UUID NOT NULL, -- SOURCE STREAM IDENTIFIER 
	REJ_STR_ID UUID, -- REJECTION STREAM IDENTIFIER
	CONSTRAINT PK_FD_STG_SYSTBL PRIMARY KEY (FD_ID),
	CONSTRAINT FK_FD_STG_CRT_PROV FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_FD_STG_UPD_PROV FOREIGN KEY (UPD_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_FD_STG_OBSLT_PROV FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT CK_FD_STS_CS CHECK (STS_CS BETWEEN 0 AND 5)
 );

 CREATE TABLE FD_ISS_SYSTBL (
	FD_ISS_ID UUID NOT NULL DEFAULT uuid_generate_v1(), -- UNIQUE IDENTIFIER OF THE ISSUE
	FD_ID UUID NOT NULL,  -- THE IDENTIFIER OF THE STAGED IMPORT TO WHICH THIS ISSUE APPLIES
	ISS_PRI INTEGER NOT NULL, -- THE PRIORITY OF THE ISSUE
	ISS_TXT VARCHAR(512) NOT NULL, -- THE TEXT OF THE ISSUE
	ISS_ID VARCHAR(128), -- ISSUE IDENTIFIER GIVEN BY THE IMPORTER
	ISS_TYP_CD UUID, -- THE ISSUE TYPE
	CONSTRAINT PK_FD_ISS_SYSTBL PRIMARY KEY (FD_ISS_ID),
	CONSTRAINT FK_FD_ISS_ID FOREIGN KEY (FD_ID) REFERENCES FD_STG_SYSTBL(FD_ID)
 );

 select reg_patch('20221130-01');