/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230802-01" name="Update:20230802-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="npgsql">
 *	<summary>Update: Adds application encryption master key (for ALE) configuration functions</summary>
 *	<isInstalled>select ck_patch('20230802-01')</isInstalled>
 * </feature>
 */

CREATE TABLE ALE_SYSTBL (
	ALE_SMK BYTEA NOT NULL -- MASTER KEY FOR THIS DATABASE
);

CREATE OR REPLACE FUNCTION HAS_ALE() RETURNS BOOLEAN AS 
$$
BEGIN
	RETURN EXISTS (SELECT * FROM ALE_SYSTBL);
END
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION GET_ALE_SMK() RETURNS BYTEA AS 
$$
BEGIN
	RETURN (SELECT ALE_SMK FROM ALE_SYSTBL LIMIT 1);
END
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION SET_ALE_SMK(NEW_ALE_SMK_IN BYTEA) RETURNS VOID AS 
$$
BEGIN
	DELETE FROM ALE_SYSTBL;
	INSERT INTO ALE_SYSTBL VALUES (NEW_ALE_SMK_IN);
END
$$ LANGUAGE PLPGSQL;

-- EXPAND THE MAX LENGTH
-- OPTIONAL
ALTER TABLE ENT_ADDR_CMP_TBL ALTER COLUMN VAL TYPE VARCHAR(1024);--#!
-- OPTIONAL
ALTER TABLE ENT_NAME_CMP_TBL ALTER COLUMN VAL TYPE VARCHAR(1024);--#!
-- OPTIONAL
ALTER TABLE ENT_TEL_TBL ALTER COLUMN TEL_VAL TYPE VARCHAR(1024);--#!
-- OPTIONAL
ALTER TABLE ENT_ID_TBL ALTER COLUMN ID_VAL TYPE VARCHAR(1024);--#!

SELECT REG_PATCH('20230802-01'); 
