/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230906-01" name="Update:20230906-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="npgsql">
 *	<summary>Update: Refactors the clinical repository data tables to separate definitions from clinical data about the protocol</summary>
 *	<isInstalled>select ck_patch('20230906-01')</isInstalled>
 * </feature>
 */
 ALTER TABLE PROTO_TBL DROP COLUMN DEFN;
 ALTER TABLE PROTO_TBL  DROP COLUMN RPLC_PROTO_ID;
 ALTER TABLE PROTO_TBL DROP COLUMN HDLR_CLS;
 ALTER TABLE PROTO_TBL DROP COLUMN GROUP_ID;
 
 CREATE SEQUENCE CDSS_AST_VRSN_SEQ START WITH 1 INCREMENT BY 1;

 CREATE TABLE CDSS_AST_SYSTBL (
	AST_ID UUID NOT NULL DEFAULT UUID_GENERATE_V1(),
	CLS_CS INT NOT NULL DEFAULT 1 CHECK (CLS_CS IN (1,2)),
	CONSTRAINT PK_CDSS_AST_DEF_SYSTBL PRIMARY KEY (AST_ID)
 );

 CREATE TABLE CDSS_AST_VRSN_SYSTBL (
	AST_VRSN_ID UUID NOT NULL DEFAULT UUID_GENERATE_V1(),
	VRSN_SEQ_ID INT NOT NULL DEFAULT NEXTVAL('cdss_ast_vrsn_seq'),
	RPLC_VRSN_ID UUID,
	HEAD BOOLEAN NOT NULL DEFAULT TRUE,
	AST_ID UUID NOT NULL,
	MNEMONIC VARCHAR(256) NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	OID VARCHAR(256) NOT NULL,
	DESCR TEXT,
	DEFN BYTEA NOT NULL,
	HDLR_CLS VARCHAR(256) NOT NULL,
	CRT_PROV_ID UUID NOT NULL,
	CRT_UTC TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	OBSLT_PROV_ID UUID,
	OBSLT_UTC TIMESTAMPTZ,
	CONSTRAINT PK_CDSS_AST_DEF_VRSN_SYSTBL PRIMARY KEY (AST_VRSN_ID),
	CONSTRAINT FK_CDSS_AST_DEF_RPLC_ID FOREIGN KEY (RPLC_VRSN_ID) REFERENCES CDSS_AST_VRSN_SYSTBL(AST_VRSN_ID),
	CONSTRAINT FK_CDSS_AST_DEF_VRSN_DEF FOREIGN KEY (AST_ID) REFERENCES CDSS_AST_SYSTBL(AST_ID),
	CONSTRAINT FK_CDSS_AST_DEF_CRT_PROV FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_CDSS_AST_DEF_OBSLT_PROV FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_CDSS_AST_STATE CHECK (OBSLT_PROV_ID IS NULL AND OBSLT_UTC IS NULL OR OBSLT_PROV_ID IS NOT NULL AND OBSLT_UTC IS NOT NULL)
);

CREATE UNIQUE INDEX CDSS_AST_DEF_VRSN_OID_UQ_IDX ON CDSS_AST_VRSN_SYSTBL(OID) WHERE (HEAD);
CREATE UNIQUE INDEX CDSS_AST_DEF_VRSN_MNEMONIC_UQ_IDX ON CDSS_AST_VRSN_SYSTBL(MNEMONIC) WHERE (HEAD);
CREATE UNIQUE INDEX CDSS_AST_DEF_VRSN_HEAD_IDX ON CDSS_AST_VRSN_SYSTBL(AST_ID, HEAD);

CREATE TABLE CDSS_GRP_SYSTBL (
	GRP_ID UUID NOT NULL DEFAULT UUID_GENERATE_V1(),
	NAME VARCHAR(256) NOT NULL,
	OID VARCHAR(256) NOT NULL,
	CRT_PROV_ID UUID NOT NULL,
	CRT_UTC TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPD_PROV_ID UUID,
	UPD_UTC TIMESTAMPTZ,
	OBSLT_PROV_ID UUID,
	OBSLT_UTC TIMESTAMPTZ,
	CONSTRAINT PK_CDSS_AST_GRP_SYSTBL PRIMARY KEY (GRP_ID),
	CONSTRAINT FK_CDSS_AST_GRP_CRT_PROV FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_CDSS_AST_GRP_OBSLT_PROV FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_CDSS_AST_GRP_UPD_PROV FOREIGN KEY (UPD_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID)
);

CREATE UNIQUE INDEX CDSS_GRP_OID_UQ_IDX ON CDSS_GRP_SYSTBL(OID) WHERE (OBSLT_UTC IS NULL);

CREATE TABLE CDSS_AST_GRP_ASSOC_SYSTBL (
	AST_ASSOC_ID UUID NOT NULL DEFAULT UUID_GENERATE_V1(),
	AST_ID UUID NOT NULL,
	GRP_ID UUID NOT NULL,
	CONSTRAINT PK_CDSS_AST_DEF_GRP_ASSOC_SYSTBL PRIMARY KEY (AST_ASSOC_ID),
	CONSTRAINT FK_CDSS_AST_DEF_GRP_PROTO FOREIGN KEY (AST_ID) REFERENCES CDSS_AST_SYSTBL(AST_ID),
	CONSTRAINT FK_CDSS_AST_DEF_GRP_GRP FOREIGN KEY (GRP_ID) REFERENCES CDSS_GRP_SYSTBL(GRP_ID)
);

SELECT REG_PATCH('20230906-01'); 
