/** 
 * <feature scope="SanteDB.Persistence.Data" id="20240521-01" name="Update:20240521-01" environment="Server Gateway"  invariantName="npgsql">
 *	<summary>Update: Adds entity extension scope column and URI/Name separation</summary>
 *	<isInstalled>select ck_patch('20240521-01')</isInstalled>
 * </feature>
 */

 ALTER TABLE EXT_TYP_TBL RENAME EXT_NAME TO EXT_URI;
 ALTER TABLE EXT_TYP_TBL ADD EXT_NAME VARCHAR(256);
 DROP INDEX IF EXISTS EXT_TYP_NAME_IDX;
 CREATE UNIQUE INDEX EXT_TYP_URI_IDX ON EXT_TYP_TBL(EXT_URI);
 CREATE TABLE EXT_TYP_SCP_TBL (
	EXT_TYP_ID UUID NOT NULL, 
	CLS_CD_ID UUID NOT NULL,
	CONSTRAINT PK_EXT_TYP_SCP_TBL PRIMARY KEY (EXT_TYP_ID, CLS_CD_ID),
	CONSTRAINT FK_EXT_TYP_SCP_EXT_TYP FOREIGN KEY (EXT_TYP_ID) REFERENCES EXT_TYP_TBL(EXT_TYP_ID),
	CONSTRAINT FK_EXT_TYP_SCP_CLS_CD FOREIGN KEY (CLS_CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT CK_EXT_TYP_CLS_CD CHECK (IS_CD_SET_MEM(CLS_CD_ID, 'ActClass') OR IS_CD_SET_MEM(CLS_CD_ID, 'EntityClass'))
);

 SELECT REG_PATCH('20240521-01'); 
