/** 
 * <feature scope="SanteDB.Persistence.Data" id="20260812-01" name="Update:20260812-01"   invariantName="npgsql" >
 *	<summary>Update: Add classification code to security policy</summary>
 *	<isInstalled>select ck_patch('20260812-01')</isInstalled>
 * </feature>
 */

 
ALTER TABLE SEC_POL_TBL ADD CLS_CD_ID UUID;
ALTER TABLE SEC_POL_TBL ADD CONSTRAINT FK_SEC_POL_CLS_CD_ID FOREIGN KEY (CLS_CD_ID) REFERENCES CD_TBL(CD_ID);

-- DELETE EXISTING DUPLICATES (NO FOR LOOP HERE SO WE JUST TRY THREE TIMES UNTIL THERE ARE NO DUPLICATES)
DELETE FROM ENT_POL_ASSOC_TBL WHERE SEC_POL_INST_ID IN (SELECT FIRST(SEC_POL_INST_ID) FROM ENT_POL_ASSOC_TBL GROUP BY ENT_ID, POL_ID HAVING COUNT(SEC_POL_INST_ID) > 1);
DELETE FROM ENT_POL_ASSOC_TBL WHERE SEC_POL_INST_ID IN (SELECT FIRST(SEC_POL_INST_ID) FROM ENT_POL_ASSOC_TBL GROUP BY ENT_ID, POL_ID HAVING COUNT(SEC_POL_INST_ID) > 1);
DELETE FROM ENT_POL_ASSOC_TBL WHERE SEC_POL_INST_ID IN (SELECT FIRST(SEC_POL_INST_ID) FROM ENT_POL_ASSOC_TBL GROUP BY ENT_ID, POL_ID HAVING COUNT(SEC_POL_INST_ID) > 1);

CREATE UNIQUE INDEX uq_ent_pol_assoc_idx ON ent_pol_assoc_tbl (ent_id, pol_id) WHERE obslt_vrsn_seq_id IS NULL;
CREATE UNIQUE INDEX uq_act_pol_assoc_idx ON act_pol_assoc_tbl (act_id, pol_id) WHERE obslt_vrsn_seq_id IS NULL;

SELECT REG_PATCH('20260812-01');