/*
 * Copyright (C) 2021 - 2024, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: fyfej
 * Date: 2023-6-21
 */
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.Model.Mail
{
    /// <summary>
    /// Mailbox to Mail message association
    /// </summary>
    [Table("mail_box_msg_assoc_tbl")]
    public class DbMailboxMessageAssociation : DbAssociation
    {

        /// <summary>
        /// Gets or sets the key of the mailbox association
        /// </summary>
        [Column("mail_box_msg_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// The source of the relationship
        /// </summary>
        [Column("mail_box_id"), ForeignKey(typeof(DbMailbox), nameof(DbMailbox.Key)), NotNull]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Gets the target key for the relationship
        /// </summary>
        [Column("mail_msg_id"), ForeignKey(typeof(DbMailMessage), nameof(DbMailMessage.Key))]
        public Guid TargetKey { get; set; }

        /// <summary>
        /// Gets or sets the mail status
        /// </summary>
        [Column("sts"), NotNull]
        public int MailStatusFlag { get; set; }
    }
}
