/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230411-01" name="Update:20230411-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="FirebirdSQL">
 *	<summary>Update: Removes needless identifier type table</summary>
 *	<isInstalled>select ck_patch('20230411-01') from rdb$database</isInstalled>
 * </feature>
 */
 
 -- COPY EXISTING TYPES
 -- OPTIONAL
ALTER TABLE ENT_ID_TBL DROP CONSTRAINT FK_ENT_ID_ID_TYP_ID;--#!
 -- OPTIONAL
ALTER TABLE ACT_ID_TBL DROP CONSTRAINT FK_ACT_ID_ID_TYP_ID;--#!
ALTER TABLE ENT_ID_TBL ADD TYP_CD_ID UUID; --#!
ALTER TABLE ACT_ID_TBL ADD TYP_CD_ID UUID; --#!
UPDATE ENT_ID_TBL SET TYP_CD_ID = (SELECT ID_TYP_TBL.TYP_CD_ID FROM ID_TYP_TBL WHERE ENT_ID_TBL.ID_TYP_ID = ID_TYP_TBL.ID_TYP_ID);--#!
UPDATE ACT_ID_TBL SET TYP_CD_ID = (SELECT ID_TYP_TBL.TYP_CD_ID FROM ID_TYP_TBL WHERE ACT_ID_TBL.ID_TYP_ID = ID_TYP_TBL.ID_TYP_ID);--#!
ALTER TABLE ENT_ID_TBL DROP ID_TYP_ID;--#!
ALTER TABLE ACT_ID_TBL DROP ID_TYP_ID;--#!

-- DROP THE TABLE
DROP TABLE ID_TYP_TBL;--#!

-- APPLY FOREIGN KEYS
ALTER TABLE ENT_ID_TBL ADD CONSTRAINT FK_ENT_ID_ID_TYP_ID FOREIGN KEY (TYP_CD_ID) REFERENCES CD_TBL(CD_ID);--#!
ALTER TABLE ACT_ID_TBL ADD CONSTRAINT FK_ACT_ID_ID_TYP_ID FOREIGN KEY (TYP_CD_ID) REFERENCES CD_TBL(CD_ID);--#!

-- APPLY CHECK CONSTRAINTS
ALTER TABLE ENT_ID_TBL ADD CONSTRAINT CK_ENT_ID_TYP_CS CHECK (TYP_CD_ID IS NULL OR CK_IS_CD_SET_MEM(TYP_CD_ID, 'IdentifierType', TRUE));--#!
ALTER TABLE ACT_ID_TBL ADD CONSTRAINT CK_ACT_ID_TYP_CS CHECK (TYP_CD_ID IS NULL OR CK_IS_CD_SET_MEM(TYP_CD_ID, 'IdentifierType', TRUE));--#!

SELECT REG_PATCH('20230411-01') FROM RDB$DATABASE; 