/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230413-01" name="Update:20230411-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="FirebirdSQL">
 *	<summary>Update: Adds Datamart Metadata Tables</summary>
 *	<isInstalled>select ck_patch('20230413-01') from rdb$database</isInstalled>
 * </feature>
 */
 
CREATE TABLE BI_DM_REG_SYSTBL (
	DM_ID UUID NOT NULL, 
	PUB_ID VARCHAR(128) NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	DESCR BLOB SUB_TYPE TEXT,
	VER VARCHAR(24) NOT NULL,
	CRT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- THE TIME THAT THE AA WAS CREATED
	CRT_PROV_ID UUID NOT NULL, -- THE USER WHICH CREATED THE AA
	OBSLT_UTC TIMESTAMP, -- THE TIME THAT THE AA WAS OBSOLETED
	OBSLT_PROV_ID UUID, -- THE USER WHICH OBSOLETED THE AA
	UPD_UTC TIMESTAMP, -- TIME THAT WAS UPDATED
	UPD_PROV_ID UUID, -- USER WHICH UPDATED
	CONSTRAINT PK_DI_DM_REG_SYSTBL PRIMARY KEY (DM_ID),
	CONSTRAINT FK_DI_DM_REG_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_DI_DM_REG_UPD_PROV_ID FOREIGN KEY (UPD_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_DI_DM_REG_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT CK_DI_DM_REG_OBSLT_PROV_ID CHECK (OBSLT_PROV_ID IS NOT NULL AND OBSLT_UTC IS NOT NULL OR OBSLT_PROV_ID IS NULL AND OBSLT_UTC IS NULL)
);--#!

CREATE UNIQUE INDEX UQ_BI_DM_REG_PUB_IDX ON BI_DM_REG_SYSTBL(PUB_ID);--#!

CREATE TABLE BI_DM_EXE_SYSTBL (
	EXE_ID UUID NOT NULL,
	DM_ID UUID NOT NULL,
	START_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	TYP_CS INT NOT NULL, 
	OUTC_CS INT NOT NULL,
	END_UTC TIMESTAMP,
	CRT_PROV_ID UUID NOT NULL,
	DIAG_STR_ID UUID,
	CONSTRAINT PK_BI_DM_EXE_SYSTBL PRIMARY KEY (EXE_ID),
	CONSTRAINT FK_BI_DM_EXE_DM_TBL FOREIGN KEY (DM_ID) REFERENCES BI_DM_REG_SYSTBL(DM_ID),
	CONSTRAINT FK_BI_DM_EXE_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID)
); --#! 
CREATE INDEX BI_DM_EXE_DM_ID_IDX ON BI_DM_EXE_SYSTBL(DM_ID);--#!

CREATE TABLE BI_DM_LOG_SYSTBL (
	LOG_ID UUID NOT NULL, 
	EXE_ID UUID NOT NULL,
	PRI_CS INT NOT NULL,
	UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	TXT BLOB SUB_TYPE TEXT NOT NULL,
	CONSTRAINT PK_BI_DM_LOG_SYSTBL PRIMARY KEY (LOG_ID),
	CONSTRAINT FK_BI_DM_EXE_ID_TBL FOREIGN KEY (EXE_ID) REFERENCES BI_DM_EXE_SYSTBL(EXE_ID)
);--#!

CREATE INDEX BI_DM_LOG_EXE_ID_IDX ON BI_DM_LOG_SYSTBL(EXE_ID);--#!
ALTER TABLE PROTO_TBL ADD GROUP_ID VARCHAR(128);--#!

SELECT REG_PATCH('20230413-01') FROM RDB$DATABASE; --#!