/** 
 * <feature scope="SanteDB.Persistence.Data" id="20230514-01" name="Update:20230514-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="FirebirdSQL">
 *	<summary>Update: Added creation time fields to the REL_VRFY_SYSTBL</summary>
 *	<isInstalled>select ck_patch('20230514-01') from rdb$database</isInstalled>
 * </feature>
 */
 
 ALTER TABLE REL_VRFY_SYSTBL ADD CRT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ;--#!
 ALTER TABLE REL_VRFY_SYSTBL ADD CRT_PROV_ID UUID DEFAULT CHAR_TO_UUID('fadca076-3690-4a6e-af9e-f1cd68e8c7e8') NOT NULL; --#!
 ALTER TABLE REL_VRFY_SYSTBL ADD CONSTRAINT FK_CRT_PROV_TBL FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID);--#!
 ALTER TABLE REL_VRFY_SYSTBL ADD OBSLT_UTC TIMESTAMP;--#!
 ALTER TABLE REL_VRFY_SYSTBL ADD OBSLT_PROV_ID UUID;--#!
 ALTER TABLE REL_VRFY_SYSTBL ADD CONSTRAINT FK_OBSLT_PROV_TBL FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID); --#!
SELECT REG_PATCH('20230514-01') FROM RDB$DATABASE; 
