/** 
 * <feature scope="SanteDB.Persistence.Data" id="20250210-01" name="Update:20250210-01"   invariantName="FirebirdSQL">
 *	<summary>Update: Add concept extensions and tags</summary>
 *	<isInstalled>select ck_patch('20250210-01') from rdb$database</isInstalled>
 * </feature>
 */
 
 
CREATE TABLE CD_TAG_TBL (
	TAG_ID UUID NOT NULL,
	CD_ID UUID NOT NULL,
	TAG_NAME VARCHAR(64) NOT NULL,
	TAG_VALUE BLOB SUB_TYPE TEXT,
	CRT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CRT_PROV_ID UUID NOT NULL,
	OBSLT_UTC TIMESTAMP,	
	OBSLT_PROV_ID UUID,
	CONSTRAINT CK_CD_TAG_OBSLT_USR CHECK ((((OBSLT_PROV_ID IS NULL) AND (OBSLT_UTC IS NULL)) OR ((OBSLT_PROV_ID IS NOT NULL) AND (OBSLT_UTC IS NOT NULL)))),
	CONSTRAINT PK_CD_TAG_TBL PRIMARY KEY (TAG_ID),
	CONSTRAINT FK_CD_TAG_CD_ID FOREIGN KEY (CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_CD_TAG_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_CD_TAG_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID)
); --#!

CREATE INDEX CD_TAG_CD_ID_IDX ON CD_TAG_TBL(CD_ID);--#!


CREATE TABLE CD_EXT_TBL (
	CD_EXT_ID UUID NOT NULL,
	CD_ID UUID NOT NULL,
	EXT_TYP_ID UUID NOT NULL,
	EXT_VAL BLOB,
	EXT_DISP BLOB SUB_TYPE TEXT,
	EFFT_VRSN_SEQ_ID INT NOT NULL,
	OBSLT_VRSN_SEQ_ID INT,
	CONSTRAINT PK_CD_EXT_TBL PRIMARY KEY (CD_EXT_ID),
	CONSTRAINT FK_CD_EXT_CD_ID FOREIGN KEY (CD_ID) REFERENCES CD_TBL(CD_ID),
	CONSTRAINT FK_CD_EXT_EXT_TYP_ID FOREIGN KEY (EXT_TYP_ID) REFERENCES EXT_TYP_TBL(EXT_TYP_ID),
	CONSTRAINT FK_CD_EXT_OBSLT_VRSN_SEQ_ID FOREIGN KEY (OBSLT_VRSN_SEQ_ID) REFERENCES CD_VRSN_TBL(VRSN_SEQ_ID),
	CONSTRAINT FK_CD_EXT_TBL_EFFT_VRSN_SEQ_ID FOREIGN KEY (EFFT_VRSN_SEQ_ID) REFERENCES CD_VRSN_TBL(VRSN_SEQ_ID)
);--#!
CREATE INDEX CD_EXT_CD_ID ON CD_EXT_TBL (CD_ID);--#!
CREATE INDEX CD_EXT_VRSN_IDX ON CD_EXT_TBL(EFFT_VRSN_SEQ_ID, OBSLT_VRSN_SEQ_ID);--#!

 SELECT REG_PATCH('20250210-01') FROM RDB$DATABASE;--#! 