/** 
 * <feature scope="SanteDB.Persistence.Data" id="20250831-01" name="Update:20250831-01"   invariantName="FirebirdSQL" >
 *	<summary>Update: Adds date observation type to CDR database</summary>
 *	<isInstalled>select ck_patch('20250831-01') from rdb$database</isInstalled>
 * </feature>
 */
 

 CREATE TABLE DT_OBS_TBL (
	ACT_VRSN_ID UUID NOT NULL, -- THE VERSION TO WHICH THE OBSERVATION DTA APPLIES
	VAL_DT TIMESTAMP, -- THE CONCEPT WHICH REPRESENTS THE VALUE
	VAL_PREC CHAR(1),
	CONSTRAINT PK_DT_OBS_TBL PRIMARY KEY (ACT_VRSN_ID),
	CONSTRAINT FK_DT_OBS_ACT_VRSN_ID FOREIGN KEY (ACT_VRSN_ID) REFERENCES OBS_TBL(ACT_VRSN_ID)
 );
 --#!
 DROP INDEX OBS_VAL_TYP_IDX;

 --#!
 ALTER TABLE OBS_TBL ADD TMP_VAL_TYP VARCHAR(2);
 --#!
 UPDATE OBS_TBL SET TMP_VAL_TYP = VAL_TYP;
 --#!
 ALTER TABLE OBS_TBL DROP VAL_TYP;
 --#!
 ALTER TABLE OBS_TBL ADD VAL_TYP VARCHAR(2) CHECK (VAL_TYP IN ('PQ','ST','TS','CD'));
 --#!
 UPDATE OBS_TBL SET VAL_TYP = TMP_VAL_TYP;
 --#!
 ALTER TABLE OBS_TBL DROP TMP_VAL_TYP;
 --#!
 SELECT REG_PATCH('20250831-01') FROM RDB$DATABASE;