/*
 * Copyright (C) 2021 - 2026, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: fyfej
 * Date: 2023-6-21
 */
using SanteDB.BI.Model;
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represents a BI definition stored in the database
    /// </summary>
    [Table("bi_def_systbl")]
    public class DbBiDefinition : DbIdentified
    {

        /// <summary>
        /// Gets or sets the key of the BI definition
        /// </summary>
        [Column("bi_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the type of BI definition
        /// </summary>
        [Column("typ"), NotNull]
        public String Type { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the BI version
        /// </summary>
        [Column("pub_id"), NotNull]
        public string Id { get; set; }

    }

    /// <summary>
    /// Represents a single version of the definition
    /// </summary>
    [Table("bi_def_vrsn_systbl")]
    public class DbBiDefinitionVersion : DbVersionedData
    {
        /// <summary>
        /// Gets or sets the version key
        /// </summary>
        [Column("vrsn_id"), PrimaryKey, NotNull, AutoGenerated]
        public override Guid VersionKey { get; set; }

        /// <summary>
        /// The BI definition to which this version belongs
        /// </summary>
        [Column("bi_id"), NotNull, ForeignKey(typeof(DbBiDefinition), nameof(DbBiDefinition.Key)), AlwaysJoin]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the BI definition status
        /// </summary>
        [Column("sts"), NotNull]
        public BiDefinitionStatus Status { get; set; }

        /// <summary>
        /// Gets or sets the name of the definition
        /// </summary>
        [Column("name")]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the definition contents
        /// </summary>
        [Column("def")]
        public byte[] DefinitionContents { get; set; }

    }

    /// <summary>
    /// A simple query result
    /// </summary>
    public class DbBiQueryResult : DbBiDefinitionVersion
    {

        /// <summary>
        /// Gets or sets the type of BI definition
        /// </summary>
        [Column("typ", DeclaredTable = typeof(DbBiDefinition)), NotNull]
        public String Type { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the BI version
        /// </summary>
        [Column("pub_id", DeclaredTable = typeof(DbBiDefinition)), NotNull]
        public string Id { get; set; }
    }
}
