using SanteDB.BI.Model;
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represents a BI definition stored in the database
    /// </summary>
    [Table("bi_def_systbl")]
    public class DbBiDefinition : DbIdentified
    {

        /// <summary>
        /// Gets or sets the key of the BI definition
        /// </summary>
        [Column("bi_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the type of BI definition
        /// </summary>
        [Column("typ"), NotNull]
        public String Type { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the BI version
        /// </summary>
        [Column("pub_id"), NotNull]
        public string Id { get; set; }

    }

    /// <summary>
    /// Represents a single version of the definition
    /// </summary>
    [Table("bi_def_vrsn_systbl")]
    public class DbBiDefinitionVersion : DbVersionedData
    {
        /// <summary>
        /// Gets or sets the version key
        /// </summary>
        [Column("vrsn_id"), PrimaryKey, NotNull, AutoGenerated]
        public override Guid VersionKey { get; set; }

        /// <summary>
        /// The BI definition to which this version belongs
        /// </summary>
        [Column("bi_id"), NotNull, ForeignKey(typeof(DbBiDefinition), nameof(DbBiDefinition.Key))]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the BI definition status
        /// </summary>
        [Column("sts"), NotNull]
        public BiDefinitionStatus Status { get; set; }

        /// <summary>
        /// Gets or sets the name of the definition
        /// </summary>
        [Column("name")]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the definition contents
        /// </summary>
        [Column("def")]
        public byte[] DefinitionContents { get; set; }

    }

    /// <summary>
    /// A simple query result
    /// </summary>
    public class DbBiQueryResult : DbBiDefinitionVersion
    {

        /// <summary>
        /// Gets or sets the type of BI definition
        /// </summary>
        [Column("typ"), NotNull]
        public String Type { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the BI version
        /// </summary>
        [Column("pub_id"), NotNull]
        public string Id { get; set; }
    }
}
