using SanteDB.Core.Cdss;
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represents a clinical protocol asset
    /// </summary>
    [Table("cdss_ast_systbl"), AssociativeTable(typeof(DbCdssGroup), typeof(DbAssetGroupAssociation))]
    public class DbCdssAsset : DbIdentified
    {
      
        /// <summary>
        /// The protocol identifier
        /// </summary>
        [Column("ast_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Clinical protocol asset class
        /// </summary>
        [Column("cls_cs"), NotNull]
        public CdssAssetClassification Classification { get; set; }

    }

    /// <summary>
    /// Protocol version system table
    /// </summary>
    [Table("cdss_ast_vrsn_systbl")]
    public class DbCdssAssetVersion : DbVersionedData
    {
        /// <summary>
        /// Gets the version key 
        /// </summary>
        [Column("ast_vrsn_id"), PrimaryKey, AutoGenerated]
        public override Guid VersionKey { get; set; }

        /// <summary>
        /// Get the key 
        /// </summary>
        [Column("ast_id"), ForeignKey(typeof(DbCdssAsset), nameof(DbCdssAsset.Key))]
        public override Guid Key { get; set; }

        /// <summary>
        /// The mnemonic/unique identifier for the object
        /// </summary>
        [Column("mnemonic"), NotNull]
        public String Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the protocol definition
        /// </summary>
        [Column("name"), NotNull]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the OID of the protocol definition
        /// </summary>
        [Column("oid"), NotNull, Unique]
        public String Oid { get; set; }

        /// <summary>
        /// Gets or sets the description
        /// </summary>
        [Column("descr")]
        public String Description { get; set; }

        /// <summary>
        /// Gets or sets the definition 
        /// </summary>
        [Column("defn"), NotNull]
        public byte[] Definition { get; set; }

        /// <summary>
        /// Gets or sets the handler class
        /// </summary>
        [Column("hdlr_cls"), NotNull]
        public String HandlerClass { get; set; }
    }

    /// <summary>
    /// Protocol asset group
    /// </summary>
    [Table("cdss_grp_systbl")]
    public class DbCdssGroup : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the primary identifier
        /// </summary>
        [Column("grp_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets the name of the grouping
        /// </summary>
        [Column("name"), NotNull]
        public string Name { get; set; }

        /// <summary>
        /// Gets the oid of the grouping
        /// </summary>
        [Column("oid"), NotNull, Unique]
        public string Oid { get; set; }
    }

    /// <summary>
    /// Links groups to protocols
    /// </summary>
    [Table("cdss_ast_grp_assoc_systbl")]
    public class DbAssetGroupAssociation : DbAssociation
    {
        /// <summary>
        /// Gets the source key
        /// </summary>
        [Column("proto_id"), ForeignKey(typeof(DbCdssAsset), nameof(DbCdssAsset.Key)), NotNull]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Gets the key of the association
        /// </summary>
        [Column("proto_assoc_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// The group of the association
        /// </summary>
        [Column("grp_id"), ForeignKey(typeof(DbCdssGroup), nameof(DbCdssGroup.Key))]
        public Guid GroupKey { get; set; }
    }

}
