using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represents a data storage of a CDSS library 
    /// </summary>
    [Table("cdss_lib_tbl")]
    public class DbCdssLibrary : DbIdentified
    {
        /// <inheritdoc/>
        [Column("lib_id"), PrimaryKey, NotNull, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Identifies the CDSS library format
        /// </summary>
        [Column("cls"), NotNull]
        public string CdssLibraryFormat { get; set; }

    }

    /// <summary>
    /// Represents an individual version of the CDSS logic
    /// </summary>
    [Table("cdss_lib_vrsn_tbl")]
    public class DbCdssLibraryVersion : DbVersionedData
    {

        /// <inheritdoc/>
        [Column("lib_id"), ForeignKey(typeof(DbCdssLibrary), nameof(DbCdssLibrary.Key))]
        public override Guid Key { get; set; }

        /// <inheritdoc/>
        [Column("lib_vrsn_id"), PrimaryKey, AutoGenerated]
        public override Guid VersionKey { get; set; }

        /// <summary>
        /// Gets or sets the named identifier of the library
        /// </summary>
        [Column("id"), NotNull]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the long form name
        /// </summary>
        [Column("name"), NotNull]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the informational version
        /// </summary>
        [Column("ver")]
        public string VersionName { get; set; }

        /// <summary>
        /// Gets or sets the OID of the library
        /// </summary>
        [Column("oid")]
        public string Oid { get; set; }

        /// <summary>
        /// Gets or sets the informational documentation
        /// </summary>
        [Column("doc")]
        public string Documentation { get; set; }

        /// <summary>
        /// Gets or sets the source data
        /// </summary>
        [Column("def"), NotNull]
        public byte[] Definition { get; set; }
    
    }
}
