/*
 * Copyright (C) 2021 - 2024, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: fyfej
 * Date: 2023-6-21
 */
using SanteDB.OrmLite.Attributes;
using System;
using System.Diagnostics.Tracing;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represents a single log entry
    /// </summary>
    [Table("BI_DM_LOG_SYSTBL")]
    public class DbDatamartLogEntry : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("LOG_ID"), NotNull, PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// The correlation key to correlate executions and logs
        /// </summary>
        [Column("EXE_ID"), NotNull, ForeignKey(typeof(DbDatamartExecutionEntry), nameof(DbDatamartExecutionEntry.Key))]
        public Guid ExecutionContextId { get; set; }

        /// <summary>
        /// Gets or sets the type of the log entry
        /// </summary>
        [Column("PRI_CS"), NotNull]
        public EventLevel Priority { get; set; }

        /// <summary>
        /// Gets or sets the start time
        /// </summary>
        [Column("UTC"), AutoGenerated, NotNull]
        public DateTimeOffset Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the text for the log
        /// </summary>
        [Column("TXT"), NotNull]
        public string Text { get; set; }

    }
}
