using SanteDB.OrmLite.Attributes;
using System;
using System.Diagnostics.Tracing;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represents a single log entry
    /// </summary>
    [Table("BI_DM_LOG_SYSTBL")]
    public class DbDatamartLogEntry : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("LOG_ID"), NotNull, PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// The correlation key to correlate executions and logs
        /// </summary>
        [Column("EXE_ID"), NotNull, ForeignKey(typeof(DbDatamartExecutionEntry), nameof(DbDatamartExecutionEntry.Key))]
        public Guid ExecutionContextId { get; set; }

        /// <summary>
        /// Gets or sets the type of the log entry
        /// </summary>
        [Column("PRI_CS"), NotNull]
        public EventLevel Priority { get; set; }

        /// <summary>
        /// Gets or sets the start time
        /// </summary>
        [Column("UTC"), AutoGenerated, NotNull]
        public DateTimeOffset Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the text for the log
        /// </summary>
        [Column("TXT"), NotNull]
        public string Text { get; set; }

    }
}
