using SanteDB.Core.Data.Import;
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// A table which represents a datamart registration
    /// </summary>
    [Table("BI_DM_REG_SYSTBL")]
    public class DbDatamartRegistration : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the the key of the foreign data element
        /// </summary>
        [Column("DM_ID"), PrimaryKey, NotNull, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets the ID
        /// </summary>
        [Column("PUB_ID"), NotNull]
        public String Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the datamart
        /// </summary>
        [Column("NAME"), NotNull]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the name of the staged data
        /// </summary>
        [Column("DESCR")]
        public String Description { get; set; }

        /// <summary>
        /// Gets or sets the version of the datamart definition last registered 
        /// </summary>
        [Column("VER"), NotNull]
        public String Version { get; set; }

    }
}
