using SanteDB.Core.Data.Import;
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Foreign data stage
    /// </summary>
    [Table("FD_STG_SYSTBL")]
    public class DbForeignDataStage : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the the key of the foreign data element
        /// </summary>
        [Column("FD_ID"), PrimaryKey, NotNull, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the name of the staged data
        /// </summary>
        [Column("NAME"), NotNull]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the status
        /// </summary>
        [Column("STS_CS"), NotNull]
        public ForeignDataStatus Status { get; set; }

        /// <summary>
        /// Gets or sets the foreign data map to use
        /// </summary>
        [Column("FD_MAP_ID"), NotNull]
        public Guid ForeignDataMapKey { get; set; }

        /// <summary>
        /// Gets or sets the source stream key
        /// </summary>
        [Column("SRC_STR_ID"), NotNull]
        public Guid SourceStreamKey { get; set; }

        /// <summary>
        /// Gets or sets the reject stream key
        /// </summary>
        [Column("REJ_STR_ID")]
        public Guid? RejectStreamKey { get; set; }
    }
}
