using SanteDB.Core.BusinessRules;
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Foreign data detected issue
    /// </summary>
    [Table("FD_ISS_SYSTBL")]
    public class DbForeignDataIssue : DbAssociation
    {
        /// <summary>
        /// Gets the key of the foreign data issue
        /// </summary>
        [Column("FD_ISS_ID"), PrimaryKey, NotNull, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets the source key to which the status pplies
        /// </summary>
        [Column("FD_ID"), ForeignKey(typeof(DbForeignDataStage), nameof(DbForeignDataStage.Key)), NotNull]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Gets or sets the priority
        /// </summary>
        [Column("ISS_PRI"), NotNull]
        public DetectedIssuePriorityType Priority { get; set; }

        /// <summary>
        /// Gets or sets the text
        /// </summary>
        [Column("ISS_TXT"), NotNull]
        public String Text { get; set; }

        /// <summary>
        /// Gets or sets the identifier given to the issue by the caller
        /// </summary>
        [Column("ISS_ID"), NotNull]
        public String LogicalId { get; set; }

        /// <summary>
        /// Gets or sets the type key
        /// </summary>
        [Column("ISS_TYP_CD"), NotNull]
        public Guid IssueTypeKey { get; set; }
    }
}
