/*
 * Copyright (C) 2021 - 2023, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: fyfej
 * Date: 2023-5-19
 */
using SanteDB.Core.Jobs;
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represents a job state entry which can easily be shared among application hosts
    /// </summary>
    [Table("job_stat_systbl")]
    public class DbJobState : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key of the job state id
        /// </summary>
        [Column("job_st_id"), PrimaryKey, AutoGenerated, NotNull]
        public override Guid Key { get; set; }

        /// <summary>
        /// Job identifier
        /// </summary>
        [Column("job_id"), NotNull]
        public Guid JobId { get; set; }

        /// <summary>
        /// Gets or sets the last status of the job
        /// </summary>
        [Column("stat"), NotNull]
        public JobStateType LastState { get; set; }

        /// <summary>
        /// Gets or sets the last start time of the job
        /// </summary>
        [Column("last_start_utc")]
        public DateTimeOffset? LastStart { get; set; }

        /// <summary>
        /// Gets or sets the last stop
        /// </summary>
        [Column("last_stop_utc")]
        public DateTimeOffset? LastStop { get; set; }
        public bool LastStopSpecified { get; internal set; }
    }
}
