using SanteDB.Core.Jobs;
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represents a job state entry which can easily be shared among application hosts
    /// </summary>
    [Table("job_stat_systbl")]
    public class DbJobState : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key of the job state id
        /// </summary>
        [Column("job_st_id"), PrimaryKey, AutoGenerated, NotNull]
        public override Guid Key { get; set; }

        /// <summary>
        /// Job identifier
        /// </summary>
        [Column("job_id"), NotNull]
        public Guid JobId { get; set; }

        /// <summary>
        /// Gets or sets the last status of the job
        /// </summary>
        [Column("stat"), NotNull]
        public JobStateType LastState { get; set; }

        /// <summary>
        /// Gets or sets the last start time of the job
        /// </summary>
        [Column("last_start_utc")]
        public DateTimeOffset? LastStart { get; set; }

        /// <summary>
        /// Gets or sets the last stop
        /// </summary>
        [Column("last_stop_utc")]
        public DateTimeOffset? LastStop { get; set; }
        public bool LastStopSpecified { get; internal set; }
    }
}
