using SanteDB.Core.Configuration;
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.Model.Sys
{
    /// <summary>
    /// Represetns a job schedule that is stored in the database
    /// </summary>
    [Table("job_sch_systbl")]
    public class DbJobScheule : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the key of the job schedule
        /// </summary>
        [Column("job_sch_id"), PrimaryKey, AutoGenerated, NotNull]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the job identifier
        /// </summary>
        [Column("job_id"), NotNull]
        public Guid JobId { get; set; }

        /// <summary>
        /// Gets or sets the schedule type
        /// </summary>
        [Column("typ"), NotNull]
        public JobScheduleType Type { get; set; }

        /// <summary>
        /// Gets or sets the interval of the job
        /// </summary>
        [Column("ivl")]
        public String Interval { get; set; }

        /// <summary>
        /// Gets or sets the time when the schedule is effective
        /// </summary>
        [Column("start_utc"), NotNull]
        public DateTimeOffset StartTime { get; set; }

        /// <summary>
        /// Gets or sets the stop time
        /// </summary>
        [Column("stop_utc")]
        public DateTimeOffset? StopTime { get; set; }

        /// <summary>
        /// Gets or sets the days
        /// </summary>
        [Column("dow")]
        public byte[] Days { get; set; }

        /// <summary>
        /// Allows the ORM to set a null value over top of a column value
        /// </summary>
        public bool DaysSpecified { get; set; }
        /// <summary>
        /// Allows the ORM to set a null value over top of a column value
        /// </summary>
        public bool IntervalSpecified { get; set; }
        /// <summary>
        /// Allows the ORM to set a null value over top of a column value
        /// </summary>
        public bool StopTimeSpecified { get; set; }
    }
}
