using SanteDB.Core.Model.DataTypes;
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.Model.Concepts
{

    /// <summary>
    /// Concept set reference association
    /// </summary>
    [Table("cd_set_comp_assoc_tbl")]
    public class DbConceptSetComposition : IDbAssociation, IDbIdentified
    {
        /// <summary>
        /// The source of this association
        /// </summary>
        [Column("set_id"), ForeignKey(typeof(DbConceptSet), nameof(DbConceptSet.Key))]
        public Guid SourceKey { get; set; }

        /// <summary>
        /// Gets or sets the concept identifier.
        /// </summary>
        /// <value>The concept identifier.</value>
        [Column("trg_set_id"), ForeignKey(typeof(DbConceptSet), nameof(DbConceptSet.Key))]
        public Guid TargetKey { get; set; }

        /// <summary>
        /// Reference role
        /// </summary>
        [Column("rol_cs")]
        public ConceptSetCompositionOperation Operation { get; set; }

        /// <summary>
        /// Gets or sets the compisition key
        /// </summary>
        [Column("set_comp_id"), PrimaryKey, AutoGenerated]
        public Guid Key { get; set; }

        /// <summary>
        /// Determine equality of this relationship and another
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is DbConceptSetComposition cso)
            {
                return cso.SourceKey == this.SourceKey &&
                    cso.TargetKey == this.TargetKey &&
                    cso.Operation == this.Operation;
            }
            else
            {
                return base.Equals(obj);
            }
        }
    }
}
