/*
 * Copyright (C) 2021 - 2024, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: fyfej
 * Date: 2023-6-21
 */
using SanteDB.Core.Model.DataTypes;
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.Model.Concepts
{

    /// <summary>
    /// Concept set reference association
    /// </summary>
    [Table("cd_set_comp_assoc_tbl")]
#pragma warning disable CS0659 // Type overrides Object.Equals(object o) but does not override Object.GetHashCode()
    public class DbConceptSetComposition : IDbAssociation, IDbIdentified
    {
        /// <summary>
        /// The source of this association
        /// </summary>
        [Column("set_id"), ForeignKey(typeof(DbConceptSet), nameof(DbConceptSet.Key))]
        public Guid SourceKey { get; set; }

        /// <summary>
        /// Gets or sets the concept identifier.
        /// </summary>
        /// <value>The concept identifier.</value>
        [Column("trg_set_id"), ForeignKey(typeof(DbConceptSet), nameof(DbConceptSet.Key))]
        public Guid TargetKey { get; set; }

        /// <summary>
        /// Reference role
        /// </summary>
        [Column("rol_cs")]
        public ConceptSetCompositionOperation Operation { get; set; }

        /// <summary>
        /// Gets or sets the compisition key
        /// </summary>
        [Column("set_comp_id"), PrimaryKey, AutoGenerated]
        public Guid Key { get; set; }

        /// <summary>
        /// Determine equality of this relationship and another
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is DbConceptSetComposition cso)
            {
                return cso.SourceKey == this.SourceKey &&
                    cso.TargetKey == this.TargetKey &&
                    cso.Operation == this.Operation;
            }
            else
            {
                return base.Equals(obj);
            }
        }
    }
#pragma warning restore CS0659 // Type overrides Object.Equals(object o) but does not override Object.GetHashCode()
}
