using SanteDB.Core.Model.Audit;
using SanteDB.Core.PubSub;
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Text;

namespace SanteDB.Persistence.PubSub.ADO.Data.Model
{
    /// <summary>
    /// Used for tracking the version/key of the processing for a channel
    /// </summary>
    [Table("sub_log_tbl")]
    public class DbSubscriptionProcessLog 
    {

        /// <summary>
        /// Get or sets the key of the process log
        /// </summary>
        [PrimaryKey, AutoGenerated, Column("sub_log_id")]
        public Guid Key { get; set; }

        /// <summary>
        /// Subscription key
        /// </summary>
        [Column("sub_id"), ForeignKey(typeof(DbSubscription), nameof(DbSubscription.Key))]
        public Guid SubscriptionKey { get; set; }

        /// <summary>
        /// Gets or sets the object key 
        /// </summary>
        [Column("obj_id")]
        public Guid ObjectKey { get; set; }

        /// <summary>
        /// Version sequence that was sent
        /// </summary>
        [Column("vrsn_seq_id")]
        public long VersionSequence { get; set; }

        /// <summary>
        /// Gets or sets the dispatch time
        /// </summary>
        [Column("dsptch_utc"), AutoGenerated]
        public DateTimeOffset DispatchTime { get; set; }

        /// <summary>
        /// Outcome of the event
        /// </summary>
        [Column("outc")]
        public OutcomeIndicator Outcome { get; set; }

        /// <summary>
        /// Gets or sets the event type
        /// </summary>
        [Column("evt")]
        public PubSubEventType EventType { get; set; }

    }
}
